"use client";

import {useEffect,useState} from "react";
import Link from "next/link";

export default function AdminPage(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState("overview"),[message,setMessage]=useState("");
 async function load(){try{const r=await fetch("/api/admin/overview",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"forbidden");setData(d)}catch(e){setMessage(e instanceof Error?e.message:"تعذر تحميل مركز الإدارة")}}
 async function update(action:string,id:string,status:string){try{const r=await fetch("/api/admin/overview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"update_failed");setMessage("تم التحديث");await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر التحديث")}}
 useEffect(()=>{const id=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(id)},[]);
 if(!data)return <main className="stage2-page"><div className="stage2-empty"><h1>مركز إدارة المنصة</h1><p>{message||"جارٍ التحقق من صلاحيات المنصة…"}</p><Link href="/" className="btn">الرئيسية</Link></div></main>;
 const tabs=[["overview","نظرة عامة"],["tenants","التجار والمؤسسات"],["plans","الباقات"],["screens","الشاشات"],["media","الإعلانات الرقمية"],["providers","المصادر"],["alerts","التنبيهات"],["audit","التدقيق"]];
 return <main className="stage2-page">
  <header className="stage2-page-head"><div><div className="eyebrow">إدارة المنصة</div><h1>مركز إدارة المنصة</h1><p>إدارة التجار والمحلات والفروع والمستخدمين والشاشات والحملات والمصادر والتدقيق من طبقة المنصة.</p></div><Link href="/dashboard/operations" className="btn">تشغيل التاجر</Link></header>
  <nav className="stage2-tabs">{tabs.map(t=><button key={t[0]} className={tab===t[0]?"active":""} onClick={()=>setTab(t[0])}>{t[1]}</button>)}</nav>
  {message&&<div className="stage2-alert">{message}</div>}
  {tab==="overview"&&<section className="stage2-kpis">
    <div><span>Organizations</span><strong>{data.orgs.length}</strong></div><div><span>Stores</span><strong>{data.stores.length}</strong></div><div><span>Branches</span><strong>{data.branches.length}</strong></div><div><span>Members</span><strong>{data.members.length}</strong></div>
    <div><span>Screens</span><strong>{data.screens.length}</strong></div><div><span>Campaigns</span><strong>{data.campaigns.length}</strong></div><div><span>Alerts</span><strong>{data.alerts.length}</strong></div><div><span>Plans</span><strong>{data.plans.length}</strong></div><div><span>Subscriptions</span><strong>{data.subscriptions.length}</strong></div><div><span>Audit events</span><strong>{data.audits.length}</strong></div>
  </section>}
  {tab==="tenants"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>المؤسسة</th><th>المتاجر</th><th>الفروع</th><th>الأعضاء</th><th>الإنشاء</th></tr></thead><tbody>{data.orgs.map((o:any)=><tr key={o.id}><td><strong>{o.name}</strong><br/><small>{o.slug}</small></td><td>{data.stores.filter((s:any)=>s.organization_id===o.id).length}</td><td>{data.branches.filter((b:any)=>b.organization_id===o.id).length}</td><td>{data.members.filter((m:any)=>m.organization_id===o.id).length}</td><td>{new Date(o.created_at).toLocaleDateString("ar-OM")}</td></tr>)}</tbody></table></div></section>}
  {tab==="plans"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>الباقة</th><th>الحالة</th><th>المؤسسات</th><th>الاشتراكات</th></tr></thead><tbody>{(data.plans||[]).map((p:any)=><tr key={p.id}><td><strong>{p.name||p.code}</strong><br/><small>{p.code}</small></td><td>{String(p.active)}</td><td>{(data.subscriptions||[]).filter((s:any)=>s.plan_id===p.id).length}</td><td>{(data.subscriptions||[]).filter((s:any)=>s.plan_id===p.id && ["active","trialing","grace_period"].includes(s.status)).length}</td></tr>)}</tbody></table></div></section>}

  {tab==="screens"&&<section className="stage2-section"><div className="stage2-grid two">{data.screens.map((s:any)=><article className="stage2-panel" key={s.id}><div className="stage2-panel-head"><h2>{s.name}</h2><span className="stage2-badge">{s.status}</span></div><p>{data.stores.find((x:any)=>x.id===s.store_id)?.name||"—"} · {s.template}</p><small>Last seen: {s.last_seen_at?new Date(s.last_seen_at).toLocaleString("ar-OM"):"—"} · Snapshot: {s.last_snapshot_at?new Date(s.last_snapshot_at).toLocaleString("ar-OM"):"—"}</small></article>)}</div></section>}
  {tab==="media"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>الحملة</th><th>المعلن</th><th>الحالة</th><th>الظهور</th><th>النقرات</th><th>التحكم</th></tr></thead><tbody>{data.campaigns.map((c:any)=><tr key={c.id}><td>{c.title}</td><td>{c.advertiser_name}</td><td>{c.status}</td><td>{c.impressions}</td><td>{c.clicks}</td><td><select value={c.status} onChange={e=>void update("campaign_status",c.id,e.target.value)}><option>pending</option><option>approved</option><option>active</option><option>paused</option><option>completed</option><option>cancelled</option></select></td></tr>)}</tbody></table></div></section>}
  {tab==="providers"&&<section className="stage2-section"><div className="stage2-grid two">{data.providers.map((p:any)=><article className="stage2-panel" key={p.code}><div className="stage2-panel-head"><h2>{p.name}</h2><span className="stage2-badge">{p.enabled?"مفعّل":"معطّل"}</span></div><p>الاستخدام التجاري: {String(p.commercial_use)} · العرض العام: {String(p.public_display)} · عرض العملاء: {String(p.customer_display)}</p><small>إعادة التوزيع: {String(p.redistribution)} · لحظي: {String(p.realtime)}</small></article>)}</div></section>}
  {tab==="alerts"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>القاعدة</th><th>النوع</th><th>نشطة</th><th>آخر تشغيل</th></tr></thead><tbody>{data.alerts.map((a:any)=><tr key={a.id}><td>{a.name}</td><td>{a.rule_type}</td><td>{String(a.active)}</td><td>{a.last_triggered_at?new Date(a.last_triggered_at).toLocaleString("ar-OM"):"—"}</td></tr>)}</tbody></table></div></section>}
  {tab==="audit"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>الوقت</th><th>الإجراء</th><th>الكيان</th><th>المنفذ</th></tr></thead><tbody>{data.audits.map((a:any,i:number)=><tr key={a.id||i}><td>{a.created_at?new Date(a.created_at).toLocaleString("ar-OM"):"—"}</td><td>{a.action||a.event_type||"—"}</td><td>{a.entity_type||a.entity_id||"—"}</td><td>{a.actor_id||a.user_id||"—"}</td></tr>)}</tbody></table></div></section>}
 </main>
}
