"use client";

import {useEffect,useState} from "react";
import Link from "next/link";

export default function AdminPage(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState("overview"),[message,setMessage]=useState("");
 async function load(){try{const r=await fetch("/api/admin/overview",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"forbidden");setData(d)}catch(e){setMessage(e instanceof Error?e.message:"تعذر تحميل مركز الإدارة")}}
 async function update(action:string,id:string,status:string){try{const r=await fetch("/api/admin/overview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"update_failed");setMessage("تم التحديث");await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر التحديث")}}
 useEffect(()=>{const id=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(id)},[]);
 if(!data)return <main className="stage2-page"><div className="stage2-empty"><h1>Platform Control Center</h1><p>{message||"جارٍ التحقق من صلاحيات المنصة…"}</p><Link href="/" className="btn">الرئيسية</Link></div></main>;
 const tabs=[["overview","Overview"],["tenants","Tenants"],["screens","Screens"],["media","DOOH"],["providers","Sources"],["alerts","Alerts"],["audit","Audit"]];
 return <main className="stage2-page">
  <header className="stage2-page-head"><div><div className="eyebrow">MASTER ADMIN</div><h1>Platform Control Center</h1><p>إدارة التجار والمحلات والفروع والمستخدمين والشاشات والحملات والمصادر والتدقيق من طبقة المنصة.</p></div><Link href="/dashboard/operations" className="btn">Merchant Operations</Link></header>
  <nav className="stage2-tabs">{tabs.map(t=><button key={t[0]} className={tab===t[0]?"active":""} onClick={()=>setTab(t[0])}>{t[1]}</button>)}</nav>
  {message&&<div className="stage2-alert">{message}</div>}
  {tab==="overview"&&<section className="stage2-kpis">
    <div><span>Organizations</span><strong>{data.orgs.length}</strong></div><div><span>Stores</span><strong>{data.stores.length}</strong></div><div><span>Branches</span><strong>{data.branches.length}</strong></div><div><span>Members</span><strong>{data.members.length}</strong></div>
    <div><span>Screens</span><strong>{data.screens.length}</strong></div><div><span>Campaigns</span><strong>{data.campaigns.length}</strong></div><div><span>Alerts</span><strong>{data.alerts.length}</strong></div><div><span>Audit events</span><strong>{data.audits.length}</strong></div>
  </section>}
  {tab==="tenants"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>Organization</th><th>Stores</th><th>Branches</th><th>Members</th><th>Created</th></tr></thead><tbody>{data.orgs.map((o:any)=><tr key={o.id}><td><strong>{o.name}</strong><br/><small>{o.slug}</small></td><td>{data.stores.filter((s:any)=>s.organization_id===o.id).length}</td><td>{data.branches.filter((b:any)=>b.organization_id===o.id).length}</td><td>{data.members.filter((m:any)=>m.organization_id===o.id).length}</td><td>{new Date(o.created_at).toLocaleDateString("ar-OM")}</td></tr>)}</tbody></table></div></section>}
  {tab==="screens"&&<section className="stage2-section"><div className="stage2-grid two">{data.screens.map((s:any)=><article className="stage2-panel" key={s.id}><div className="stage2-panel-head"><h2>{s.name}</h2><span className="stage2-badge">{s.status}</span></div><p>{data.stores.find((x:any)=>x.id===s.store_id)?.name||"—"} · {s.template}</p><small>Last seen: {s.last_seen_at?new Date(s.last_seen_at).toLocaleString("ar-OM"):"—"} · Snapshot: {s.last_snapshot_at?new Date(s.last_snapshot_at).toLocaleString("ar-OM"):"—"}</small></article>)}</div></section>}
  {tab==="media"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>Campaign</th><th>Advertiser</th><th>Status</th><th>Impressions</th><th>Clicks</th><th>Control</th></tr></thead><tbody>{data.campaigns.map((c:any)=><tr key={c.id}><td>{c.title}</td><td>{c.advertiser_name}</td><td>{c.status}</td><td>{c.impressions}</td><td>{c.clicks}</td><td><select value={c.status} onChange={e=>void update("campaign_status",c.id,e.target.value)}><option>pending</option><option>approved</option><option>active</option><option>paused</option><option>completed</option><option>cancelled</option></select></td></tr>)}</tbody></table></div></section>}
  {tab==="providers"&&<section className="stage2-section"><div className="stage2-grid two">{data.providers.map((p:any)=><article className="stage2-panel" key={p.code}><div className="stage2-panel-head"><h2>{p.name}</h2><span className="stage2-badge">{p.enabled?"Enabled":"Disabled"}</span></div><p>Commercial: {String(p.commercial_use)} · Public: {String(p.public_display)} · Customer: {String(p.customer_display)}</p><small>Redistribution: {String(p.redistribution)} · Realtime: {String(p.realtime)}</small></article>)}</div></section>}
  {tab==="alerts"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>Rule</th><th>Type</th><th>Active</th><th>Last triggered</th></tr></thead><tbody>{data.alerts.map((a:any)=><tr key={a.id}><td>{a.name}</td><td>{a.rule_type}</td><td>{String(a.active)}</td><td>{a.last_triggered_at?new Date(a.last_triggered_at).toLocaleString("ar-OM"):"—"}</td></tr>)}</tbody></table></div></section>}
  {tab==="audit"&&<section className="stage2-section"><div className="stage2-table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Actor</th></tr></thead><tbody>{data.audits.map((a:any,i:number)=><tr key={a.id||i}><td>{a.created_at?new Date(a.created_at).toLocaleString("ar-OM"):"—"}</td><td>{a.action||a.event_type||"—"}</td><td>{a.entity_type||a.entity_id||"—"}</td><td>{a.actor_id||a.user_id||"—"}</td></tr>)}</tbody></table></div></section>}
 </main>
}
