import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";const read=p=>readFileSync(p,"utf8");
test("Stage 3 adapters fail closed and are provider agnostic",()=>{assert.match(read("lib/stage3/ai.ts"),/ai_not_configured/);assert.match(read("lib/stage3/whatsapp.ts"),/whatsapp_not_configured/);assert.match(read("lib/stage3/payments.ts"),/payments_not_configured/);assert.match(read("lib/stage3/einvoice.ts"),/einvoice_not_configured/);assert.match(read("lib/stage3/payments.ts"),/assertTransition/);});
test("Webhook verification and secrets boundaries exist",()=>{for(const p of["lib/stage3/whatsapp.ts","lib/stage3/payments.ts","lib/stage3/einvoice.ts"])assert.match(read(p),/createHmac|timingSafeEqual/);assert.doesNotMatch(read("supabase/migrations/20260918014000_gmp_stage3_integrations.sql"),/card_number|cvv|pan/i);});
test("Stage 3 database layer is additive and tenant scoped",()=>{for(const p of["supabase/migrations/20260918014000_gmp_stage3_integrations.sql","supabase/migrations/20260918015500_gmp_stage3_security_hardening.sql"])assert.doesNotMatch(read(p),/drop table|truncate table|delete from/i);const s=read("supabase/migrations/20260918014000_gmp_stage3_integrations.sql");for(const key of["gmp_ai_jobs","gmp_whatsapp_messages","gmp_billing_events","gmp_api_usage_events","gmp_einvoice_attempts"])assert.match(s,new RegExp(key));assert.match(s,/organization_id uuid/);});
test("Stage 3 scope hardening protects cross-tenant references",()=>{const s=read("supabase/migrations/20260918015500_gmp_stage3_security_hardening.sql");for(const key of["cross_tenant_document_reference","cross_tenant_subscription_reference","cross_tenant_payment_reference","cross_tenant_api_key_reference"])assert.match(s,new RegExp(key));});
test("Subscription lifecycle state machine covers failure, grace, suspension and reactivation",()=>{const s=read("lib/stage3/payments.ts");for(const key of["past_due","grace_period","suspended","active","canceled"])assert.match(s,new RegExp(key));});
test("PWA shell is present and offline never caches API routes",()=>{assert.match(read("app/manifest.ts"),/standalone/);assert.match(read("app/PwaRegister.tsx"),/serviceWorker\.register/);assert.match(read("public/sw.js"),/pathname\.startsWith\("\/api\/"\)/);});
test("Developer API v2 has auth, IDs and usage telemetry",()=>{assert.match(read("app/api/v2/market/gold/route.ts"),/authenticateApiKey/);assert.match(read("app/api/v2/market/gold/route.ts"),/recordApiUsage/);assert.match(read("app/api/v2/market/gold/route.ts"),/request_id/);assert.match(read("lib/stage3/developer-api.ts"),/gmp_api_usage_events/);});

test("Stage 3 UI exposes real integration states and webhook management",()=>{const page=read("app/dashboard/integrations/page.tsx");const workspace=read("app/dashboard/integrations/Stage3Workspace.tsx");assert.match(page,/aiState=\{ai\.state\}/);assert.match(page,/whatsappState=\{wa\.state\}/);assert.match(workspace,/\{aiState\}/);assert.match(workspace,/\{whatsappState\}/);assert.match(read("app/dashboard/api-keys/page.tsx"),/WebhooksWorkspace/);assert.match(read("app/api/dashboard/webhooks/route.ts"),/encryptWebhookSecret/);assert.match(read("app/dashboard/api-keys/WebhooksWorkspace.tsx"),/market\.alert\.triggered/);assert.doesNotMatch(read("app/dashboard/api-keys/WebhooksWorkspace.tsx"),/secret_ciphertext/);});
