import Link from "next/link";
import { getSnapshot } from "../lib/providers";
import { countries, languages } from "../lib/config";

export default async function Home({ searchParams }: { searchParams?: Promise<{ country?: string; language?: string }> }) {
  const params = await searchParams;
  const country = countries.find(c => c.code === params?.country) ?? countries[0];
  const language = languages.some(l => l.code === params?.language) ? params?.language! : 'ar';
  const snapshot = await getSnapshot(country.currency, language, false);
  const gold = snapshot.gold;
  return <div className="app-shell">
    <header className="topbar"><div className="container nav"><Link href="/" className="brand">GLOBAL <span>MARKET</span></Link><nav className="nav-links"><Link href="/gold">Gold</Link><Link href="/silver">Silver</Link><Link href="/markets">Markets</Link><Link href="/stocks">Stocks</Link><Link href="/news">News</Link></nav><div className="nav-actions"><Link className="btn btn-ghost" href="/login">تسجيل الدخول</Link><Link className="btn btn-primary" href="/demo">أنشئ شاشة</Link></div></div></header>
    <main>
      <div className="container section"><form className="preference-bar" method="get"><label className="label">الدولة<select className="select" name="country" defaultValue={country.code}>{countries.map(c => <option value={c.code} key={c.code}>{c.name} · {c.currency}</option>)}</select></label><label className="label">Language<select className="select" name="language" defaultValue={language}>{languages.map(l => <option value={l.code} key={l.code}>{l.name}</option>)}</select></label><button className="btn">تطبيق</button></form></div>
      <div className="container hero"><section><div className="kicker">GLOBAL MARKET REFERENCE</div><h1>أسعار وأسواق العالم، في منصة واحدة.</h1><p className="lede">ذهب وفضة وأسواق وأسهم وأخبار مالية، مع عملة الدولة ولغة المستخدم، وبنية متعددة المصادر مع تحقق وحالة بيانات واضحة.</p><div className="nav-actions" style={{marginTop:24}}><Link href={`/gold?country=${country.code}&language=${language}`} className="btn btn-primary">شاهد الذهب</Link><Link href="/demo" className="btn">جرّب شاشة المحل</Link></div></section>
        <section className="hero-card"><div className="row"><div><div className="card-title">الذهب — {country.name}</div><div className="metric">24K / Gram</div></div><span className={`pill ${gold.status === 'LIVE' ? 'pill-live' : ''}`}>{gold.status}</span></div><div className="price-xl">{gold.purities['24K'] == null ? '—' : `${gold.purities['24K']?.toFixed(3)} ${country.currency}`}</div><div className="meta">{gold.status === 'LIVE' ? `مصدر: ${gold.provider}` : 'لا توجد بيانات حية مفعلة حاليًا'}</div><div className="kv-grid"><div className="kv"><span className="meta">Bid</span><strong>{gold.bid == null ? '—' : `${gold.bid.toFixed(2)} ${country.currency}`}</strong></div><div className="kv"><span className="meta">Ask</span><strong>{gold.ask == null ? '—' : `${gold.ask.toFixed(2)} ${country.currency}`}</strong></div></div></section>
      </div>
      <div className="container section"><div className="section-head"><div><div className="kicker">MARKETS</div><h2>الأسواق الرئيسية</h2></div><Link href="/markets" className="btn">كل الأسواق</Link></div><div className="grid grid-4">{snapshot.markets.length ? snapshot.markets.map(q => <div className="card" key={q.instrument}><div className="card-title">{q.instrument}</div><div className="metric">{q.spot?.toLocaleString()}</div><div className="meta">{q.status} · {q.currency}</div></div>) : <div className="notice" style={{gridColumn:'1/-1'}}>بيانات المؤشرات الحية غير مفعلة حاليًا. لن تعرض المنصة أرقامًا تجريبية على أنها سوق حقيقي.</div>}</div></div>
      <div className="container section"><div className="section-head"><div><div className="kicker">POPULAR STOCKS</div><h2>الأسهم الرئيسية</h2></div><Link href="/stocks" className="btn">بحث الأسهم</Link></div><div className="grid grid-4">{snapshot.stocks.length ? snapshot.stocks.map(q => <div className="card" key={q.instrument}><div className="card-title">{q.instrument}</div><div className="metric">${q.spot?.toFixed(2)}</div><div className="meta">{q.status}</div></div>) : <div className="notice" style={{gridColumn:'1/-1'}}>مصدر الأسهم التجاري/المسموح للعرض الخارجي غير مفعّل حاليًا.</div>}</div></div>
      <div id="news" className="container section"><div className="section-head"><div><div className="kicker">TRUSTED NEWS ENGINE</div><h2>أهم الأخبار</h2></div></div><div className="card">{snapshot.news.length ? snapshot.news.map(n => <article className="news-item" key={n.id}><div style={{flex:1}}><div className="row"><div className="news-title">{n.title}</div><span className={`pill ${n.status === 'LIVE' ? 'pill-live' : ''}`}>{n.status}</span></div><div className="news-meta">{n.source} · {n.category} · {n.language}</div></div></article>) : <div className="notice">لم يتم تفعيل مصدر أخبار خارجي في هذه البيئة.</div>}</div></div>
      <div className="container section"><div className="card notice"><strong>Free-first:</strong> لا يوجد أي مسار يقوم بالترقية إلى خدمة مدفوعة تلقائيًا. عند نفاد المصدر أو فشله، يستخدم النظام بديلًا أو Cache أو يعرض عدم التوفر.</div></div>
    </main><footer className="footer"><div className="container"><div>الدول في V1: {countries.map(c => c.name).join(' · ')}</div><div style={{marginTop:8}}>المعلومات مرجعية وليست خدمة وساطة أو استشارة استثمارية.</div></div></footer>
  </div>;
}
