import Link from "next/link";
import { getSnapshot } from "../lib/providers";
import { getPublicAds } from "../lib/public-ads";
import { appConfig, countries, isValidLanguage, languages } from "../lib/config";
import { getDisplayName, getMessages, isRtlLanguage } from "../lib/i18n";
import { formatMoneyDisplay } from "../lib/currency-display";

const supportedLanguageCodes = ["ar", "en", "tr", "de"] as const;

function formatMoney(value: number | null, locale: string, currency: string, maximumFractionDigits = 3) { return formatMoneyDisplay(value, currency, locale, maximumFractionDigits); }

export default async function Home({ searchParams }: { searchParams?: Promise<{ country?: string; language?: string }> }) {
  const params = await searchParams;
  const country = countries.find((c) => c.code === params?.country?.toUpperCase()) ?? countries.find((c) => c.code === appConfig.defaultCountry) ?? countries[0];
  const requestedLanguage = params?.language?.toLowerCase() ?? "";
  const language = isValidLanguage(requestedLanguage) && supportedLanguageCodes.includes(requestedLanguage as (typeof supportedLanguageCodes)[number]) ? requestedLanguage : appConfig.defaultLanguage;
  const messages = getMessages(language);
  const [snapshot, ads] = await Promise.all([getSnapshot(country.currency, language, false), getPublicAds({ country: country.code, placement: "banner", limit: 4 })]);
  const gold = snapshot.gold;
  const silver = snapshot.silver;
  const locale = `${language}-${country.code}`;
  const countryName = getDisplayName("region", country.code, language, country.name);
  const supportedLanguages = languages.filter((l) => supportedLanguageCodes.includes(l.code as (typeof supportedLanguageCodes)[number]));

  return <div className="app-shell home-page" lang={language} dir={isRtlLanguage(language) ? "rtl" : "ltr"}>
    <header className="topbar"><div className="container nav"><Link href="/" className="brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></Link><nav className="nav-links" aria-label="Primary"><Link href={`/gold?country=${country.code}&language=${language}`}>{messages.gold}</Link><Link href={`/silver?country=${country.code}&language=${language}`}>{messages.silver}</Link><Link href={`/markets?country=${country.code}&language=${language}`}>{messages.markets}</Link><Link href={`/stocks?country=${country.code}&language=${language}`}>{messages.stocks}</Link><Link href={`/currencies?country=${country.code}&language=${language}`}>{language === "ar" ? "العملات" : "Currencies"}</Link><Link href={`/news?country=${country.code}&language=${language}`}>{messages.news}</Link><Link href="/directory">{language==="ar"?"المحلات":"Stores"}</Link><Link href="/marketplace">{language === "ar" ? "السوق" : "Marketplace"}</Link></nav><div className="nav-actions"><div className="nav-preferences"><span className="country-dot" />{countryName}<span className="nav-divider" />{language.toUpperCase()}</div><Link className="btn btn-ghost" href="/login">{messages.login}</Link><Link className="btn btn-primary" href="/demo">{messages.createDisplay}</Link></div></div></header>
    {ads.length > 0 && <section className="announcement container"><span>إعلان</span>{ads.slice(0, 1).map(ad => <a href={ad.targetUrl ?? "#"} key={ad.id} target={ad.targetUrl ? "_blank" : undefined} rel={ad.targetUrl ? "noreferrer" : undefined}>{ad.title}</a>)}</section>}
    <main>
      <section className="container hero hero-premium"><div className="hero-copy-wrap"><div className="eyebrow"><span className="live-dot" />{language === "ar" ? "معلومات السوق العالمية" : "GLOBAL MARKET INTELLIGENCE"}</div><h1>{language === "ar" ? "أسعار الأسواق العالمية، بوضوح ودقة." : "Global market prices, clearly presented."}</h1><p className="lede">{language === "ar" ? "الذهب والفضة والعملات والأسواق والأخبار في تجربة واحدة مصممة للمتابعة اليومية." : "Gold, silver, currencies, markets and news in one daily monitoring experience."}</p><div className="nav-actions hero-actions"><Link href={`/gold?country=${country.code}&language=${language}`} className="btn btn-primary btn-lg">{messages.goldView}</Link><Link href={`/markets?country=${country.code}&language=${language}`} className="btn btn-lg">{language === "ar" ? "استكشف الأسواق" : "Explore markets"}</Link></div><div className="hero-note"><span>●</span>{language === "ar" ? "بيانات مرجعية • تحديث حسب المصدر" : "Reference data • source-dependent updates"}</div></div><div className="market-hero-card"><div className="market-hero-head"><div><div className="micro-label">{messages.gold} · {countryName}</div><div className="market-symbol">XAU / {country.currency}</div></div><span className={`market-status ${gold.status === "LIVE" ? "is-live" : ""}`}><span />{gold.status}</span></div><div className="market-price">{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</div><div className="market-unit">24K · {language === "ar" ? "غرام" : "Gram"}</div><div className="market-divider" /><div className="market-grid"><div><span>{language === "ar" ? "الفضة" : "Silver"}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong></div><div><span>{language === "ar" ? "مصدر البيانات" : "Data source"}</span><strong className="provider-value">{gold.provider || "غير متاح"}</strong></div><div><span>{messages.bid}</span><strong>{formatMoney(gold.bid, locale, country.currency, 2)}</strong></div><div><span>{messages.ask}</span><strong>{formatMoney(gold.ask, locale, country.currency, 2)}</strong></div></div></div></section>
      <section className="container ticker-section"><div className="ticker-label">مراقبة السوق</div><div className="ticker-grid"><Link href={`/gold?country=${country.code}&language=${language}`}><span>ذهب 24K</span><strong>{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</strong><em className="up">مباشر</em></Link><Link href={`/gold?country=${country.code}&language=${language}`}><span>ذهب 22K</span><strong>{formatMoney(gold.purities["22K"] ?? null, locale, country.currency)}</strong><em>مرجعي</em></Link><Link href={`/silver?country=${country.code}&language=${language}`}><span>{language === "ar" ? "الفضة" : "SILVER"}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong><em>مرجعي</em></Link><Link href={`/currencies?country=${country.code}&language=${language}`}><span>FX</span><strong>{language === "ar" ? "أسعار صرف" : "FX rates"}</strong><em>{language === "ar" ? "مرجعي" : "REF"}</em></Link></div></section>
      <section className="container section feature-section"><div className="section-head"><div><div className="eyebrow">الأسواق</div><h2>{language === "ar" ? "الوصول إلى السوق" : "Market access"}</h2><p className="section-lede">{language === "ar" ? "صفحات مستقلة لكل فئة، بدون ازدحام على الشاشة الرئيسية." : "Focused pages for each market category, without crowding the homepage."}</p></div><Link href={`/markets?country=${country.code}&language=${language}`} className="text-link">{language === "ar" ? "عرض الكل" : "View all"} →</Link></div><div className="market-cards"><Link className="market-card market-card-gold" href={`/gold?country=${country.code}&language=${language}`}><div className="card-icon">Au</div><div><span>{messages.gold}</span><strong>{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</strong><small>24K · Gram · {gold.status}</small></div><b>→</b></Link><Link className="market-card" href={`/silver?country=${country.code}&language=${language}`}><div className="card-icon silver">Ag</div><div><span>{messages.silver}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong><small>999 · Gram</small></div><b>→</b></Link><Link className="market-card" href={`/currencies?country=${country.code}&language=${language}`}><div className="card-icon fx">FX</div><div><span>{language === "ar" ? "العملات" : "Currencies"}</span><strong>FX</strong><small>{language === "ar" ? "أسعار صرف مرجعية" : "Reference FX rates"}</small></div><b>→</b></Link><Link className="market-card" href={`/markets?country=${country.code}&language=${language}`}><div className="card-icon index">IDX</div><div><span>{messages.markets}</span><strong>GLOBAL</strong><small>{language === "ar" ? "مؤشرات وأسواق مرجعية" : "Reference indices & markets"}</small></div><b>→</b></Link></div></section>
      <section className="container section dual-section"><div className="section-panel"><div className="eyebrow">الأسهم</div><h2>{messages.stocks}</h2><p>{language === "ar" ? "أسهم عالمية مرجعية عند تفعيل مصدر بيانات مرخّص." : "Global reference equities when a licensed data source is enabled."}</p><Link href={`/stocks?country=${country.code}&language=${language}`} className="btn">{language === "ar" ? "فتح الأسهم" : "Open equities"}</Link></div><div className="section-panel section-panel-alt"><div className="eyebrow">غرفة الأخبار</div><h2>{messages.news}</h2><p>{snapshot.news.length ? `${snapshot.news.length} ${language === "ar" ? "عناصر إخبارية متاحة" : "news items available"}.` : messages.noNews}</p><Link href={`/news?country=${country.code}&language=${language}`} className="btn">{language === "ar" ? "فتح الأخبار" : "Open news"}</Link></div></section>
      <section className="container merchant-banner"><div><div className="eyebrow">للمحلات</div><h2>{language === "ar" ? "حوّل أسعار السوق إلى شاشة احترافية لمحلّك." : "Turn market prices into a professional display for your shop."}</h2><p>{language === "ar" ? "شاشة، أسعار، عروض، وإدارة تجارية في مساحة واحدة." : "Display, prices, promotions and merchant operations in one workspace."}</p></div><div className="nav-actions"><Link href="/demo" className="btn btn-primary">{language === "ar" ? "جرّب الشاشة" : "Try the display"}</Link><Link href="/dashboard/operations" className="btn">{language === "ar" ? "مساحة التاجر" : "Merchant workspace"}</Link><Link href="/marketplace" className="btn">{language === "ar" ? "Marketplace" : "Marketplace"}</Link></div></section>
    </main>
    <footer className="footer-premium"><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></div><p>{language === "ar" ? "منصة معلومات سوقية مرجعية للأسواق والمعادن والأصول." : "Reference market information across metals, markets and assets."}</p></div><div><strong>{language === "ar" ? "الأسواق" : "Markets"}</strong><Link href={`/gold?country=${country.code}&language=${language}`}>{messages.gold}</Link><Link href={`/silver?country=${country.code}&language=${language}`}>{messages.silver}</Link><Link href={`/stocks?country=${country.code}&language=${language}`}>{messages.stocks}</Link></div><div><strong>{language === "ar" ? "المنصة" : "Platform"}</strong><Link href="/pricing">{language === "ar" ? "الباقات" : "Plans"}</Link><Link href="/directory">{language === "ar" ? "دليل المحلات" : "Store directory"}</Link><Link href="/marketplace">{language === "ar" ? "السوق" : "Marketplace"}</Link><Link href="/login">{messages.login}</Link><Link href="/demo">{messages.createDisplay}</Link></div><div><strong>{language === "ar" ? "الموقع" : "Region"}</strong><span>{countryName}</span><span>{supportedLanguages.length} {language === "ar" ? "لغات" : "languages"}</span></div></div><div className="container footer-bottom"><span>© Global Market</span><span>{messages.referenceFooter}</span></div></footer>
  </div>;
}
