import Link from "next/link";
import { cookies } from "next/headers";
import { getSnapshot } from "../lib/providers";
import { getPublicAds } from "../lib/public-ads";
import { appConfig, countries, isValidLanguage, languages, SUPPORTED_PUBLIC_LANGUAGES } from "../lib/config";
import { getDisplayName, getMessages, isRtlLanguage } from "../lib/i18n";
import MoneyDisplay from "../components/MoneyDisplay";
import DisplayPreferences from "../components/DisplayPreferences";

type SupportedLanguage = (typeof SUPPORTED_PUBLIC_LANGUAGES)[number];

function formatMoney(value: number | null, locale: string, currency: string, maximumFractionDigits = 3) { return <MoneyDisplay value={value} currency={currency} locale={locale} maximumFractionDigits={maximumFractionDigits} />; }

export default async function Home({ searchParams }: { searchParams?: Promise<{ country?: string; language?: string }> }) {
  const params = await searchParams;
  const cookieStore = await cookies();
  const initialTheme: "dark" | "light" = cookieStore.get("gmp-theme")?.value === "light" ? "light" : "dark";
  const initialFontScale: "small" | "normal" | "large" = cookieStore.get("gmp-font-scale")?.value === "small" ? "small" : cookieStore.get("gmp-font-scale")?.value === "large" ? "large" : "normal";
  const country = countries.find((c) => c.code === params?.country?.toUpperCase()) ?? countries.find((c) => c.code === appConfig.defaultCountry) ?? countries[0];
  const requestedLanguage = params?.language?.toLowerCase() ?? "";
  const language: SupportedLanguage = isValidLanguage(requestedLanguage) && SUPPORTED_PUBLIC_LANGUAGES.includes(requestedLanguage as SupportedLanguage) ? requestedLanguage as SupportedLanguage : appConfig.defaultLanguage as SupportedLanguage;
  const messages = getMessages(language);
  const [snapshot, ads] = await Promise.all([getSnapshot(country.currency, language, false), getPublicAds({ country: country.code, placement: "banner", limit: 4 })]);
  const gold = snapshot.gold;
  const silver = snapshot.silver;
  const locale = `${language}-${country.code}`;
  const countryName = getDisplayName("region", country.code, language, country.name);
  const supportedLanguages = languages.filter((l) => SUPPORTED_PUBLIC_LANGUAGES.includes(l.code as SupportedLanguage));

  return <div className="app-shell home-page" lang={language} dir={isRtlLanguage(language) ? "rtl" : "ltr"}>
    <header className="topbar"><div className="container nav"><Link href="/" className="brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></Link><nav className="nav-links" aria-label={language === "ar" ? "التنقل الرئيسي" : "Primary"}><Link href={`/gold?country=${country.code}&language=${language}`}>{messages.gold}</Link><Link href={`/silver?country=${country.code}&language=${language}`}>{messages.silver}</Link><Link href={`/markets?country=${country.code}&language=${language}`}>{messages.markets}</Link><Link href={`/stocks?country=${country.code}&language=${language}`}>{messages.stocks}</Link><Link href={`/currencies?country=${country.code}&language=${language}`}>{messages.currencies}</Link><Link href={`/news?country=${country.code}&language=${language}`}>{messages.news}</Link><Link href="/directory">{language==="ar"?"المحلات":"Stores"}</Link><Link href="/marketplace">{messages.marketplace}</Link></nav><div className="nav-actions"><DisplayPreferences language={language} initialTheme={initialTheme} initialFontScale={initialFontScale} /><div className="nav-preferences"><span className="country-dot" />{countryName}<span className="nav-divider" />{language.toUpperCase()}</div><Link className="btn btn-ghost" href="/login">{messages.login}</Link><Link className="btn btn-primary" href="/demo">{messages.createDisplay}</Link></div></div></header>
    {ads.length > 0 && <section className="announcement container"><span>{messages.announcement}</span>{ads.slice(0, 1).map(ad => <a href={ad.targetUrl ?? "#"} key={ad.id} target={ad.targetUrl ? "_blank" : undefined} rel={ad.targetUrl ? "noreferrer" : undefined}>{ad.title}</a>)}</section>}
    <main>
      <section className="container hero hero-premium"><div className="hero-copy-wrap"><div className="eyebrow"><span className="live-dot" />{messages.heroIntelligence}</div><h1>{messages.heroTitle}</h1><p className="lede">{messages.heroDescription}</p><div className="nav-actions hero-actions"><Link href={`/gold?country=${country.code}&language=${language}`} className="btn btn-primary btn-lg">{messages.goldView}</Link><Link href={`/markets?country=${country.code}&language=${language}`} className="btn btn-lg">{language === "ar" ? "استكشف الأسواق" : "Explore markets"}</Link></div><div className="hero-note"><span>●</span>{language === "ar" ? "بيانات مرجعية • تحديث حسب المصدر" : language === "tr" ? "Referans veriler • kaynağa bağlı güncellemeler" : language === "de" ? "Referenzdaten • Aktualisierung je nach Quelle" : "Reference data • source-dependent updates"}</div></div><div className="market-hero-card"><div className="market-hero-head"><div><div className="micro-label">{messages.gold} · {countryName}</div><div className="market-symbol">XAU / {country.currency}</div></div><span className={`market-status ${gold.status === "LIVE" ? "is-live" : ""}`}><span />{gold.status}</span></div><div className="market-price">{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</div><div className="market-unit">24K · {messages.gramUnit}</div><div className="market-divider" /><div className="market-grid"><div><span>{language === "ar" ? "الفضة" : "Silver"}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong></div><div><span>{messages.dataSource}</span><strong className="provider-value">{gold.provider || messages.notAvailable}</strong></div><div><span>{messages.bid}</span><strong>{formatMoney(gold.bid, locale, country.currency, 2)}</strong></div><div><span>{messages.ask}</span><strong>{formatMoney(gold.ask, locale, country.currency, 2)}</strong></div></div></div></section>
      <section className="container ticker-section"><div className="ticker-label">مراقبة السوق</div><div className="ticker-grid"><Link href={`/gold?country=${country.code}&language=${language}`}><span>ذهب 24K</span><strong>{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</strong><em className="up">{messages.direct}</em></Link><Link href={`/gold?country=${country.code}&language=${language}`}><span>ذهب 22K</span><strong>{formatMoney(gold.purities["22K"] ?? null, locale, country.currency)}</strong><em>{messages.reference}</em></Link><Link href={`/silver?country=${country.code}&language=${language}`}><span>{language === "ar" ? "الفضة" : "SILVER"}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong><em>{messages.reference}</em></Link><Link href={`/currencies?country=${country.code}&language=${language}`}><span>FX</span><strong>{language === "ar" ? "أسعار صرف" : "FX rates"}</strong><em>{messages.reference}</em></Link></div></section>
      <section className="container section feature-section"><div className="section-head"><div><div className="eyebrow">{messages.markets}</div><h2>{messages.marketAccess}</h2><p className="section-lede">{messages.marketAccessDescription}</p></div><Link href={`/markets?country=${country.code}&language=${language}`} className="text-link">{messages.viewAll} →</Link></div><div className="market-cards"><Link className="market-card market-card-gold" href={`/gold?country=${country.code}&language=${language}`}><div className="card-icon">Au</div><div><span>{messages.gold}</span><strong>{formatMoney(gold.purities["24K"] ?? null, locale, country.currency)}</strong><small>24K · {messages.gramUnit} · {gold.status}</small></div><b>→</b></Link><Link className="market-card" href={`/silver?country=${country.code}&language=${language}`}><div className="card-icon silver">Ag</div><div><span>{messages.silver}</span><strong>{formatMoney(silver.purities["999"] ?? null, locale, country.currency)}</strong><small>999 · {messages.gramUnit}</small></div><b>→</b></Link><Link className="market-card" href={`/currencies?country=${country.code}&language=${language}`}><div className="card-icon fx">FX</div><div><span>{messages.currencies}</span><strong>FX</strong><small>{language === "ar" ? "أسعار صرف مرجعية" : language === "tr" ? "Referans döviz kurları" : language === "de" ? "Referenz-Wechselkurse" : "Reference FX rates"}</small></div><b>→</b></Link><Link className="market-card" href={`/markets?country=${country.code}&language=${language}`}><div className="card-icon index">IDX</div><div><span>{messages.markets}</span><strong>GLOBAL</strong><small>{language === "ar" ? "مؤشرات وأسواق مرجعية" : language === "tr" ? "Referans endeksler ve piyasalar" : language === "de" ? "Referenzindizes und Märkte" : "Reference indices & markets"}</small></div><b>→</b></Link></div></section>
      <section className="container section dual-section"><div className="section-panel"><div className="eyebrow">الأسهم</div><h2>{messages.stocks}</h2><p>{messages.stocksIntro}</p><Link href={`/stocks?country=${country.code}&language=${language}`} className="btn">{messages.openStocks}</Link></div><div className="section-panel section-panel-alt"><div className="eyebrow">{messages.newsRoom}</div><h2>{messages.news}</h2><p>{snapshot.news.length ? `${snapshot.news.length} ${messages.availableNews}.` : messages.noNews}</p><Link href={`/news?country=${country.code}&language=${language}`} className="btn">{messages.openNews}</Link></div></section>
      <section className="container merchant-banner"><div><div className="eyebrow">{messages.shopSection}</div><h2>{messages.shopBannerTitle}</h2><p>{messages.shopBannerDescription}</p></div><div className="nav-actions"><Link href="/demo" className="btn btn-primary">{messages.tryDisplay}</Link><Link href="/dashboard/operations" className="btn">{messages.merchantWorkspace}</Link><Link href="/marketplace" className="btn">{messages.marketplace}</Link></div></section>
    </main>
    <footer className="footer-premium"><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></div><p>{language === "ar" ? "منصة معلومات سوقية مرجعية للأسواق والمعادن والأصول." : "Reference market information across metals, markets and assets."}</p></div><div><strong>{language === "ar" ? "الأسواق" : "Markets"}</strong><Link href={`/gold?country=${country.code}&language=${language}`}>{messages.gold}</Link><Link href={`/silver?country=${country.code}&language=${language}`}>{messages.silver}</Link><Link href={`/stocks?country=${country.code}&language=${language}`}>{messages.stocks}</Link></div><div><strong>{messages.platform}</strong><Link href="/pricing">{language === "ar" ? messages.plans : "Plans"}</Link><Link href="/directory">{language === "ar" ? messages.stores : "Store directory"}</Link><Link href="/marketplace">{messages.marketplace}</Link><Link href="/login">{messages.login}</Link><Link href="/demo">{messages.createDisplay}</Link></div><div><strong>{messages.region}</strong><span>{countryName}</span><span>{supportedLanguages.length} {messages.languages}</span></div></div><div className="container footer-bottom"><span>© Global Market</span><span>{messages.referenceFooter}</span></div></footer>
  </div>;
}
