export const appConfig={name:"Global Market Platform",defaultCountry:"OM",defaultCurrency:"OMR",defaultLanguage:"ar"} as const;
const ISO_COUNTRY_CODES=['AW','AF','AO','AI','AX','AL','AD','AE','AR','AM','AS','AQ','TF','AG','AU','AT','AZ','BI','BE','BJ','BQ','BF','BD','BG','BH','BS','BA','BL','BY','BZ','BM','BO','BR','BB','BN','BT','BV','BW','CF','CA','CC','CH','CL','CN','CI','CM','CD','CG','CK','CO','KM','CV','CR','CU','CW','CX','KY','CY','CZ','DE','DJ','DM','DK','DO','DZ','EC','EG','ER','EH','ES','EE','ET','FI','FJ','FK','FR','FO','FM','GA','GB','GE','GG','GH','GI','GN','GP','GM','GW','GQ','GR','GD','GL','GT','GF','GU','GY','HK','HM','HN','HR','HT','HU','ID','IM','IN','IO','IE','IR','IQ','IS','IL','IT','JM','JE','JO','JP','KZ','KE','KG','KH','KI','KN','KR','KW','LA','LB','LR','LY','LC','LI','LK','LS','LT','LU','LV','MO','MF','MA','MC','MD','MG','MV','MX','MH','MK','ML','MT','MM','ME','MN','MP','MZ','MR','MS','MQ','MU','MW','MY','YT','NA','NC','NE','NF','NG','NI','NU','NL','NO','NP','NR','NZ','OM','PK','PA','PN','PE','PH','PW','PG','PL','PR','KP','PT','PY','PS','PF','QA','RE','RO','RU','RW','SA','SD','SN','SG','GS','SH','SJ','SB','SL','SV','SM','SO','PM','RS','SS','ST','SR','SK','SI','SE','SZ','SX','SC','SY','TC','TD','TG','TH','TJ','TK','TM','TL','TO','TT','TN','TR','TV','TW','TZ','UG','UA','UM','UY','US','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','ZA','ZM','ZW'] as const;
const ISO_LANGUAGE_CODES=['aa','ab','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh','bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da','de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fj','fo','fr','fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz','ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj','kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln','lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb','nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi','pl','ps','pt','qu','rm','rn','ro','ru','sa','sc','sd','se','sg','si','sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th','ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi','vo','wa','wo','xh','yi','yo','za','zh','zu'] as const;
export type CountryCode=(typeof ISO_COUNTRY_CODES)[number];
export type LanguageCode=(typeof ISO_LANGUAGE_CODES)[number];
const regionNames=new Intl.DisplayNames(['en'],{type:'region'});
const languageNames=new Intl.DisplayNames(['en'],{type:'language'});
const defaultCurrencyByCountry:Record<string,string>={OM:'OMR',SA:'SAR',AE:'AED',US:'USD',GB:'GBP',TR:'TRY',DE:'EUR',JP:'JPY',CN:'CNY',IN:'INR',CH:'CHF',CA:'CAD',AU:'AUD',NZ:'NZD',SG:'SGD',HK:'HKD',QA:'QAR',KW:'KWD',BH:'BHD',JO:'JOD',EG:'EGP',MA:'MAD',ZA:'ZAR',NG:'NGN',BR:'BRL',MX:'MXN',AR:'ARS',CL:'CLP',CO:'COP',PE:'PEN',RU:'RUB',UA:'UAH',PL:'PLN',SE:'SEK',NO:'NOK',DK:'DKK',IS:'ISK',CZ:'CZK',HU:'HUF',RO:'RON',BG:'BGN',RS:'RSD',IL:'ILS',TH:'THB',ID:'IDR',MY:'MYR',KR:'KRW',PK:'PKR',BD:'BDT',LK:'LKR',NP:'NPR',VN:'VND',PH:'PHP',KZ:'KZT',AZ:'AZN',GE:'GEL',AM:'AMD',UZ:'UZS',IR:'IRR',IQ:'IQD',SY:'SYP',YE:'YER',LB:'LBP',TN:'TND',DZ:'DZD',LY:'LYD',SD:'SDG',KE:'KES',TZ:'TZS',UG:'UGX',GH:'GHS',ET:'ETB',ZM:'ZMW',BW:'BWP',NA:'NAD',MZ:'MZN',AO:'AOA',SN:'XOF',CI:'XOF',CM:'XAF',CG:'XAF',CD:'CDF',RW:'RWF',MU:'MUR',MG:'MGA',SC:'SCR',MV:'MVR',FJ:'FJD',PG:'PGK',WS:'WST',TO:'TOP',VU:'VUV',SB:'SBD',TT:'TTD',BB:'BBD',JM:'JMD',BS:'BSD',BZ:'BZD',CR:'CRC',PA:'PAB',GT:'GTQ',HN:'HNL',NI:'NIO',DO:'DOP',BO:'BOB',PY:'PYG',UY:'UYU',SR:'SRD'};
const countryCurrency=(code:string)=>defaultCurrencyByCountry[code]??'USD';
const countryTimezone=(code:string)=>code==='OM'?'Asia/Muscat':'UTC';
export const countries=ISO_COUNTRY_CODES.map(code=>({code,name:regionNames.of(code)??code,currency:countryCurrency(code),locale:`en-${code}`,timezone:countryTimezone(code)}));
export const languages=ISO_LANGUAGE_CODES.map(code=>({code,name:languageNames.of(code)??code}));
export function isValidLanguage(code:string|null|undefined){return !!code&&ISO_LANGUAGE_CODES.includes(code.toLowerCase() as LanguageCode)}
export function isValidCountry(code:string|null|undefined){return !!code&&ISO_COUNTRY_CODES.includes(code.toUpperCase() as CountryCode)}
export function normalizeLocale(language:string|null|undefined,country?:string|null){const lang=language?.trim().toLowerCase()||appConfig.defaultLanguage;return country&&isValidCountry(country)&&lang.length<=3?`${lang}-${country.toUpperCase()}`:lang}
export function currencyFormatter(locale:string,currency:string,minimumFractionDigits?:number){return new Intl.NumberFormat(locale,{style:'currency',currency,minimumFractionDigits})}
