const dictionaries: Record<string, Record<string, string>> = {
  ar: {
    gold:"الذهب",silver:"الفضة",markets:"الأسواق",stocks:"الأسهم",news:"الأخبار",currencies:"العملات",demo:"معاينة شاشة الأسعار",plans:"الاشتراكات",demoPreview:"معاينة شاشة المحل — اربط الشاشة من حساب التاجر بعد الاشتراك.",login:"تسجيل الدخول",signup:"إنشاء الحساب",country:"الدولة",language:"اللغة",apply:"تطبيق",createDisplay:"أنشئ شاشة",goldView:"شاهد الذهب",displayDemo:"جرّب شاشة المحل",
    referenceOnly:"السعر المرجعي فقط — ليس سعر شراء/بيع من متجر.",unavailable:"البيانات غير متاحة حاليًا",noNews:"لا يوجد مصدر أخبار خارجي مفعّل حاليًا.",referenceFooter:"معلومات مرجعية فقط. ليست وساطة أو استشارة استثمارية.",spot:"فوري",bid:"شراء مرجعي",ask:"بيع مرجعي",gram:"غرام",change:"التغير",close:"الإغلاق",percent:"النسبة",marketDataNote:"بيانات الأسواق المعروضة هي بيانات سوق مرجعية متأخرة/نهاية اليوم وفق ترخيص المصدر.",
    statusLive:"مباشر",statusDelayed:"متأخر",statusStale:"قديم",statusEstimated:"تقديري",statusUnavailable:"غير متاح",globalReference:"منصة الأسواق العالمية",
    announcement:"إعلان",marketWatch:"مراقبة السوق",dataSource:"مصدر البيانات",notAvailable:"غير متاح",direct:"مباشر",reference:"مرجعي",exploreMarkets:"استكشف الأسواق",viewAll:"عرض الكل",marketAccess:"الوصول إلى السوق",marketAccessDescription:"صفحات مستقلة لكل فئة، بدون ازدحام على الشاشة الرئيسية.",stocksIntro:"أسهم عالمية مرجعية عند تفعيل مصدر بيانات مرخّص.",openStocks:"فتح الأسهم",newsRoom:"غرفة الأخبار",openNews:"فتح الأخبار",shopSection:"للمحلات",shopBannerTitle:"حوّل أسعار السوق إلى شاشة احترافية لمحلّك.",shopBannerDescription:"شاشة، أسعار، عروض، وإدارة تجارية في مساحة واحدة.",tryDisplay:"جرّب الشاشة",merchantWorkspace:"مساحة التاجر",stores:"المحلات",marketplace:"السوق",platform:"المنصة",region:"الموقع",languages:"لغات",availableNews:"عناصر إخبارية متاحة",heroIntelligence:"معلومات السوق العالمية",gramUnit:"غرام",
    heroTitle:"الذهب والفضة والأسواق والأخبار، في منصة واحدة.",heroDescription:"بيانات مرجعية مجانية للزوار، مع أدوات تشغيل متكاملة لأصحاب المحلات."
  },
  en: {
    gold:"Gold",silver:"Silver",markets:"Markets",stocks:"Stocks",news:"News",currencies:"Currencies",demo:"Display Preview",plans:"Plans",demoPreview:"Shop display preview — connect the display from the merchant account after subscription.",login:"Login",signup:"Create account",country:"Country",language:"Language",apply:"Apply",createDisplay:"Create Display",goldView:"View gold",displayDemo:"Try the shop display",
    referenceOnly:"Reference price only — not a shop buy/sell price.",unavailable:"Data is currently unavailable",noNews:"No external news source is enabled.",referenceFooter:"Reference information only. Not brokerage or investment advice.",spot:"Spot",bid:"Bid",ask:"Ask",gram:"gram",change:"Change",close:"Close",percent:"%",marketDataNote:"Displayed market data is delayed/end-of-day reference data subject to the source license.",statusLive:"LIVE",statusDelayed:"DELAYED",statusStale:"STALE",statusEstimated:"ESTIMATED",statusUnavailable:"UNAVAILABLE",globalReference:"GLOBAL MARKET PLATFORM",
    announcement:"Announcement",marketWatch:"Market watch",dataSource:"Data source",notAvailable:"Unavailable",direct:"LIVE",reference:"Reference",exploreMarkets:"Explore markets",viewAll:"View all",marketAccess:"Market access",marketAccessDescription:"Focused pages for each market category, without crowding the home screen.",stocksIntro:"Global reference equities when a licensed data source is enabled.",openStocks:"Open equities",newsRoom:"News room",openNews:"Open news",shopSection:"For shops",shopBannerTitle:"Turn market prices into a professional display for your shop.",shopBannerDescription:"Display, prices, promotions and merchant operations in one workspace.",tryDisplay:"Try the display",merchantWorkspace:"Merchant workspace",stores:"Stores",marketplace:"Marketplace",platform:"Platform",region:"Region",languages:"languages",availableNews:"news items available",heroIntelligence:"GLOBAL MARKET INTELLIGENCE",gramUnit:"gram",
    heroTitle:"Gold, silver, markets and news in one platform.",heroDescription:"Free public reference data for visitors, with integrated operating tools for shop owners."
  },
  tr: {
    gold:"Altın",silver:"Gümüş",markets:"Piyasalar",stocks:"Hisseler",news:"Haberler",currencies:"Para Birimleri",demo:"Ekran Önizleme",plans:"Planlar",demoPreview:"Mağaza ekranı önizlemesi — abonelikten sonra ekranı mağaza hesabından bağlayın.",login:"Giriş",signup:"Hesap oluştur",country:"Ülke",language:"Dil",apply:"Uygula",createDisplay:"Ekran Oluştur",goldView:"Altını görüntüle",displayDemo:"Mağaza ekranını dene",
    referenceOnly:"Yalnızca referans fiyatı — mağaza alış/satış fiyatı değildir.",unavailable:"Veri şu anda kullanılamıyor",noNews:"Harici haber kaynağı etkin değil.",referenceFooter:"Yalnızca referans bilgileri. Aracılık veya yatırım tavsiyesi değildir.",spot:"Spot",bid:"Alış",ask:"Satış",gram:"gram",change:"Değişim",close:"Kapanış",percent:"%",marketDataNote:"Gösterilen piyasa verileri, sağlayıcı lisansına tabi gecikmeli/gün sonu referans verileridir.",statusLive:"CANLI",statusDelayed:"GECİKMELİ",statusStale:"ESKİ",statusEstimated:"TAHMİNİ",statusUnavailable:"KULLANILAMIYOR",globalReference:"GLOBAL MARKET PLATFORM",
    announcement:"Duyuru",marketWatch:"Piyasa takibi",dataSource:"Veri kaynağı",notAvailable:"Kullanılamıyor",direct:"CANLI",reference:"Referans",exploreMarkets:"Piyasaları keşfet",viewAll:"Tümünü görüntüle",marketAccess:"Piyasa erişimi",marketAccessDescription:"Ana ekranı kalabalıklaştırmadan her piyasa kategorisi için odaklanmış sayfalar.",stocksIntro:"Lisanslı bir veri kaynağı etkinleştirildiğinde küresel referans hisseleri.",openStocks:"Hisseleri aç",newsRoom:"Haber odası",openNews:"Haberleri aç",shopSection:"Mağazalar için",shopBannerTitle:"Piyasa fiyatlarını mağazanız için profesyonel bir ekrana dönüştürün.",shopBannerDescription:"Ekran, fiyatlar, kampanyalar ve mağaza operasyonları tek çalışma alanında.",tryDisplay:"Ekranı dene",merchantWorkspace:"Mağaza çalışma alanı",stores:"Mağazalar",marketplace:"Pazar yeri",platform:"Platform",region:"Bölge",languages:"dil",availableNews:"haber öğesi mevcut",heroIntelligence:"KÜRESEL PİYASA İSTİHBARATI",gramUnit:"gram",
    heroTitle:"Altın, gümüş, piyasalar ve haberler tek platformda.",heroDescription:"Ziyaretçiler için ücretsiz referans verileri ve mağaza sahipleri için entegre işletme araçları."
  },
  de: {
    gold:"Gold",silver:"Silber",markets:"Märkte",stocks:"Aktien",news:"Nachrichten",currencies:"Währungen",demo:"Display-Vorschau",plans:"Tarife",demoPreview:"Ladenanzeige-Vorschau — verbinden Sie das Display nach dem Abonnement mit dem Händlerkonto.",login:"Anmelden",signup:"Konto erstellen",country:"Land",language:"Sprache",apply:"Anwenden",createDisplay:"Display erstellen",goldView:"Gold ansehen",displayDemo:"Ladenanzeige testen",
    referenceOnly:"Nur Referenzpreis — kein An-/Verkaufspreis eines Händlers.",unavailable:"Daten derzeit nicht verfügbar",noNews:"Keine externe Nachrichtenquelle aktiviert.",referenceFooter:"Nur Referenzinformationen. Keine Anlageberatung oder Vermittlung.",spot:"Spot",bid:"Geldkurs",ask:"Briefkurs",gram:"Gramm",change:"Änderung",close:"Schlusskurs",percent:"%",marketDataNote:"Angezeigte Marktdaten sind verzögerte/Tagesenddaten nach Lizenz des Datenanbieters.",statusLive:"LIVE",statusDelayed:"VERZÖGERT",statusStale:"VERALTET",statusEstimated:"GESCHÄTZT",statusUnavailable:"NICHT VERFÜGBAR",globalReference:"GLOBAL MARKET PLATFORM",
    announcement:"Ankündigung",marketWatch:"Marktüberblick",dataSource:"Datenquelle",notAvailable:"Nicht verfügbar",direct:"LIVE",reference:"Referenz",exploreMarkets:"Märkte entdecken",viewAll:"Alle anzeigen",marketAccess:"Marktzugang",marketAccessDescription:"Fokussierte Seiten für jede Marktkategorie, ohne die Startseite zu überladen.",stocksIntro:"Globale Referenzaktien, sobald eine lizenzierte Datenquelle aktiviert ist.",openStocks:"Aktien öffnen",newsRoom:"Nachrichtenraum",openNews:"Nachrichten öffnen",shopSection:"Für Geschäfte",shopBannerTitle:"Verwandeln Sie Marktpreise in ein professionelles Display für Ihr Geschäft.",shopBannerDescription:"Display, Preise, Angebote und Händlerbetrieb in einem Arbeitsbereich.",tryDisplay:"Display testen",merchantWorkspace:"Händlerbereich",stores:"Geschäfte",marketplace:"Marktplatz",platform:"Plattform",region:"Region",languages:"Sprachen",availableNews:"Nachrichten verfügbar",heroIntelligence:"GLOBALE MARKTINFORMATIONEN",gramUnit:"Gramm",
    heroTitle:"Gold, Silber, Märkte und Nachrichten auf einer Plattform.",heroDescription:"Kostenlose Referenzdaten für Besucher und integrierte Betriebswerkzeuge für Händler."
  },
  bn: {
    gold:"সোনা",silver:"রূপা",markets:"বাজার",stocks:"শেয়ার",news:"খবর",currencies:"মুদ্রা",demo:"দাম প্রদর্শনের প্রিভিউ",plans:"প্যাকেজ",demoPreview:"দোকানের ডিসপ্লে প্রিভিউ — সাবস্ক্রাইব করার পর মার্চেন্ট অ্যাকাউন্ট থেকে ডিসপ্লে সংযুক্ত করুন।",login:"লগইন",signup:"অ্যাকাউন্ট তৈরি করুন",country:"দেশ",language:"ভাষা",apply:"প্রয়োগ",createDisplay:"ডিসপ্লে তৈরি করুন",goldView:"সোনার দাম দেখুন",displayDemo:"দোকানের ডিসপ্লে দেখুন",
    referenceOnly:"শুধু রেফারেন্স মূল্য — দোকানের ক্রয়/বিক্রয় মূল্য নয়।",unavailable:"এই মুহূর্তে ডেটা পাওয়া যাচ্ছে না",noNews:"কোনো বাহ্যিক সংবাদ উৎস সক্রিয় নেই।",referenceFooter:"শুধু রেফারেন্স তথ্য। ব্রোকারেজ বা বিনিয়োগ পরামর্শ নয়।",spot:"স্পট",bid:"রেফারেন্স ক্রয়",ask:"রেফারেন্স বিক্রয়",gram:"গ্রাম",change:"পরিবর্তন",close:"ক্লোজ",percent:"%",marketDataNote:"প্রদর্শিত বাজার ডেটা উৎসের লাইসেন্স অনুযায়ী বিলম্বিত/দিনশেষের রেফারেন্স ডেটা।",
    statusLive:"লাইভ",statusDelayed:"বিলম্বিত",statusStale:"পুরোনো",statusEstimated:"আনুমানিক",statusUnavailable:"অনুপলব্ধ",globalReference:"গ্লোবাল মার্কেট প্ল্যাটফর্ম",
    announcement:"ঘোষণা",marketWatch:"বাজার পর্যবেক্ষণ",dataSource:"ডেটা উৎস",notAvailable:"অনুপলব্ধ",direct:"লাইভ",reference:"রেফারেন্স",exploreMarkets:"বাজার দেখুন",viewAll:"সব দেখুন",marketAccess:"বাজারে প্রবেশ",marketAccessDescription:"হোম স্ক্রিন ভিড় না করে প্রতিটি বাজার শ্রেণির জন্য আলাদা পৃষ্ঠা।",stocksIntro:"লাইসেন্সপ্রাপ্ত ডেটা উৎস সক্রিয় থাকলে বৈশ্বিক রেফারেন্স শেয়ার।",openStocks:"শেয়ার খুলুন",newsRoom:"সংবাদ কক্ষ",openNews:"খবর খুলুন",shopSection:"দোকানের জন্য",shopBannerTitle:"বাজারের দামকে আপনার দোকানের পেশাদার ডিসপ্লেতে রূপান্তর করুন।",shopBannerDescription:"ডিসপ্লে, দাম, অফার এবং মার্চেন্ট অপারেশন এক কর্মক্ষেত্রে।",tryDisplay:"ডিসপ্লে চেষ্টা করুন",merchantWorkspace:"মার্চেন্ট কর্মক্ষেত্র",stores:"দোকান",marketplace:"মার্কেটপ্লেস",platform:"প্ল্যাটফর্ম",region:"অঞ্চল",languages:"ভাষা",availableNews:"টি সংবাদ আইটেম",heroIntelligence:"গ্লোবাল মার্কেট ইন্টেলিজেন্স",gramUnit:"গ্রাম",
    heroTitle:"সোনা, রূপা, বাজার ও খবর এক প্ল্যাটফর্মে।",heroDescription:"দর্শকদের জন্য বিনামূল্যের রেফারেন্স ডেটা এবং দোকান মালিকদের জন্য সমন্বিত অপারেশন টুল।"
  },
  ur: {
    gold:"سونا",silver:"چاندی",markets:"مارکیٹس",stocks:"حصص",news:"خبریں",currencies:"کرنسیاں",demo:"قیمت ڈسپلے پیش نظارہ",plans:"پیکیجز",demoPreview:"دکان ڈسپلے پیش نظارہ — سبسکرپشن کے بعد مرچنٹ اکاؤنٹ سے ڈسپلے منسلک کریں۔",login:"لاگ اِن",signup:"اکاؤنٹ بنائیں",country:"ملک",language:"زبان",apply:"لاگو کریں",createDisplay:"ڈسپلے بنائیں",goldView:"سونے کی قیمت دیکھیں",displayDemo:"دکان ڈسپلے آزمائیں",
    referenceOnly:"صرف حوالہ قیمت — دکان کی خرید/فروخت قیمت نہیں۔",unavailable:"اس وقت ڈیٹا دستیاب نہیں",noNews:"کوئی بیرونی خبر کا ذریعہ فعال نہیں۔",referenceFooter:"صرف حوالہ معلومات۔ بروکریج یا سرمایہ کاری کا مشورہ نہیں۔",spot:"اسپاٹ",bid:"حوالہ خرید",ask:"حوالہ فروخت",gram:"گرام",change:"تبدیلی",close:"اختتام",percent:"فیصد",marketDataNote:"دکھایا گیا مارکیٹ ڈیٹا فراہم کنندہ کے لائسنس کے مطابق تاخیر شدہ/دن کے اختتام کا حوالہ ڈیٹا ہے۔",
    statusLive:"براہِ راست",statusDelayed:"تاخیر شدہ",statusStale:"پرانا",statusEstimated:"تخمینی",statusUnavailable:"دستیاب نہیں",globalReference:"گلوبل مارکیٹ پلیٹ فارم",
    announcement:"اعلان",marketWatch:"مارکیٹ نگرانی",dataSource:"ڈیٹا ذریعہ",notAvailable:"دستیاب نہیں",direct:"براہِ راست",reference:"حوالہ",exploreMarkets:"مارکیٹس دیکھیں",viewAll:"سب دیکھیں",marketAccess:"مارکیٹ رسائی",marketAccessDescription:"ہوم اسکرین کو بھرے بغیر ہر مارکیٹ کیٹیگری کے لیے الگ صفحات۔",stocksIntro:"لائسنس یافتہ ڈیٹا ذریعہ فعال ہونے پر عالمی حوالہ حصص۔",openStocks:"حصص کھولیں",newsRoom:"نیوز روم",openNews:"خبریں کھولیں",shopSection:"دکانوں کے لیے",shopBannerTitle:"مارکیٹ قیمتوں کو اپنی دکان کے پیشہ ورانہ ڈسپلے میں تبدیل کریں۔",shopBannerDescription:"ڈسپلے، قیمتیں، پیشکشیں اور مرچنٹ آپریشن ایک جگہ۔",tryDisplay:"ڈسپلے آزمائیں",merchantWorkspace:"مرچنٹ ورک اسپیس",stores:"دکانیں",marketplace:"مارکیٹ پلیس",platform:"پلیٹ فارم",region:"علاقہ",languages:"زبانیں",availableNews:"خبر آئٹمز دستیاب",heroIntelligence:"عالمی مارکیٹ معلومات",gramUnit:"گرام",
    heroTitle:"سونا، چاندی، مارکیٹس اور خبریں ایک پلیٹ فارم میں۔",heroDescription:"زائرین کے لیے مفت حوالہ ڈیٹا اور دکان مالکان کے لیے مربوط آپریشن ٹولز۔"
  },
  hi: {
    gold:"सोना",silver:"चांदी",markets:"बाज़ार",stocks:"शेयर",news:"समाचार",currencies:"मुद्राएँ",demo:"मूल्य डिस्प्ले पूर्वावलोकन",plans:"प्लान",demoPreview:"दुकान डिस्प्ले पूर्वावलोकन — सदस्यता के बाद मर्चेंट खाते से डिस्प्ले जोड़ें।",login:"लॉग इन",signup:"खाता बनाएँ",country:"देश",language:"भाषा",apply:"लागू करें",createDisplay:"डिस्प्ले बनाएँ",goldView:"सोना देखें",displayDemo:"दुकान डिस्प्ले आज़माएँ",
    referenceOnly:"केवल संदर्भ मूल्य — दुकान का खरीद/बिक्री मूल्य नहीं।",unavailable:"अभी डेटा उपलब्ध नहीं है",noNews:"कोई बाहरी समाचार स्रोत सक्रिय नहीं है।",referenceFooter:"केवल संदर्भ जानकारी। ब्रोकरेज या निवेश सलाह नहीं।",spot:"स्पॉट",bid:"संदर्भ खरीद",ask:"संदर्भ बिक्री",gram:"ग्राम",change:"बदलाव",close:"क्लोज़",percent:"प्रतिशत",marketDataNote:"दिखाया गया बाज़ार डेटा स्रोत लाइसेंस के अनुसार विलंबित/दिन-अंत संदर्भ डेटा है।",
    statusLive:"लाइव",statusDelayed:"विलंबित",statusStale:"पुराना",statusEstimated:"अनुमानित",statusUnavailable:"उपलब्ध नहीं",globalReference:"ग्लोबल मार्केट प्लेटफ़ॉर्म",
    announcement:"घोषणा",marketWatch:"बाज़ार निगरानी",dataSource:"डेटा स्रोत",notAvailable:"उपलब्ध नहीं",direct:"लाइव",reference:"संदर्भ",exploreMarkets:"बाज़ार देखें",viewAll:"सभी देखें",marketAccess:"बाज़ार पहुँच",marketAccessDescription:"होम स्क्रीन को भीड़भाड़ से बचाते हुए हर बाज़ार श्रेणी के लिए अलग पृष्ठ।",stocksIntro:"लाइसेंस प्राप्त डेटा स्रोत सक्रिय होने पर वैश्विक संदर्भ शेयर।",openStocks:"शेयर खोलें",newsRoom:"समाचार कक्ष",openNews:"समाचार खोलें",shopSection:"दुकानों के लिए",shopBannerTitle:"बाज़ार कीमतों को अपनी दुकान के पेशेवर डिस्प्ले में बदलें।",shopBannerDescription:"डिस्प्ले, कीमतें, ऑफ़र और मर्चेंट संचालन एक कार्यक्षेत्र में।",tryDisplay:"डिस्प्ले आज़माएँ",merchantWorkspace:"मर्चेंट कार्यक्षेत्र",stores:"दुकानें",marketplace:"मार्केटप्लेस",platform:"प्लेटफ़ॉर्म",region:"क्षेत्र",languages:"भाषाएँ",availableNews:"समाचार आइटम उपलब्ध",heroIntelligence:"वैश्विक बाज़ार जानकारी",gramUnit:"ग्राम",
    heroTitle:"सोना, चांदी, बाज़ार और समाचार एक प्लेटफ़ॉर्म में।",heroDescription:"दर्शकों के लिए मुफ्त संदर्भ डेटा और दुकान मालिकों के लिए एकीकृत संचालन उपकरण।"
  }
};

export function getMessages(language: string) { return dictionaries[language] ?? dictionaries.en; }
export function getDisplayName(type: "region" | "language", value: string, language: string, fallback: string = value) { try { return new Intl.DisplayNames([language], { type }).of(value) ?? fallback; } catch { return fallback; } }
export function isRtlLanguage(language: string) { return ["ar","fa","he","ur"].includes(language); }
export function formatStatus(status: string, messages: Record<string,string>) { switch(status.toUpperCase()){case "LIVE":return messages.statusLive;case "DELAYED":return messages.statusDelayed;case "STALE":return messages.statusStale;case "ESTIMATED":return messages.statusEstimated;default:return messages.statusUnavailable;} }
