"use client";
import { FormEvent,useEffect,useState } from "react";
type Store={id:string;name:string;country_code:string;currency:string}; type Connector={id:string;country_code:string;provider_name:string;provider_code:string;status:string;integration_mode:string}; type Profile={id:string;store_id:string|null;country_code:string;legal_name:string|null;tax_number:string|null;registration_number:string|null;currency:string|null;vat_rate:number;e_invoice_enabled:boolean;connector_id:string|null}; type Submission={id:string;country_code:string;status:string;sale_id:string|null;external_reference:string|null;error_code:string|null;error_message:string|null;created_at:string}; type Sale={id:string;invoice_no:number;store_id:string;total:number;status:string;issued_at:string|null};
const names:Record<string,string>={OM:"عُمان",SA:"السعودية",AE:"الإمارات"}; const statuses:Record<string,string>={planned:"مخطط",ready:"جاهز",configured:"مُهيأ",active:"مفعّل",disabled:"معطل",queued:"في الطابور",sending:"جارٍ الإرسال",submitted:"تم الإرسال",accepted:"مقبولة",rejected:"مرفوضة",failed:"فشلت",cancelled:"ملغاة"};
export default function InvoicingWorkspace(){
 const[stores,setStores]=useState<Store[]>([]),[sales,setSales]=useState<Sale[]>([]),[connectors,setConnectors]=useState<Connector[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[busy,setBusy]=useState(false),[queueBusy,setQueueBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/merchant/invoicing",{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok){setMessage(d?.error??"تعذر التحميل");return;}setStores(d.stores??[]);setSales(d.sales??[]);setConnectors(d.connectors??[]);setProfiles(d.profiles??[]);setSubmissions(d.submissions??[]);};
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[]);
 const saveProfile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage("");const fd=new FormData(e.currentTarget);const entries=Object.fromEntries(fd.entries()) as Record<string,string>;const body={...entries,e_invoice_enabled:fd.has("e_invoice_enabled")};const r=await fetch("/api/merchant/invoicing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"profile",...body})});const d=await r.json().catch(()=>null);if(!r.ok)setMessage(d?.error??"تعذر حفظ إعداد الدولة");else{setMessage("تم حفظ إعدادات الفوترة");await load();}setBusy(false);};
 const queueSale=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setQueueBusy(true);setMessage("");const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/merchant/invoicing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"queue",...body})});const d=await r.json().catch(()=>null);if(!r.ok)setMessage(d?.error??"تعذر وضع الفاتورة في الطابور");else{setMessage("تم وضع الفاتورة في طابور الإرسال");e.currentTarget.reset();await load();}setQueueBusy(false);};
 return <>
 <section className="grid two"><form className="card" onSubmit={saveProfile}><div className="card-title">إعداد ملف الفوترة</div><label className="field"><span>الدولة</span><select name="country_code" defaultValue="OM"><option value="OM">عُمان</option><option value="SA">السعودية</option><option value="AE">الإمارات</option></select></label><label className="field"><span>المتجر</span><select name="store_id" defaultValue=""><option value="">اختر المتجر</option>{stores.map(s=><option value={s.id} key={s.id}>{s.name} · {names[s.country_code]??s.country_code}</option>)}</select></label><label className="field"><span>الاسم القانوني</span><input name="legal_name" maxLength={250}/></label><label className="field"><span>الرقم الضريبي</span><input name="tax_number" maxLength={100}/></label><label className="field"><span>رقم السجل</span><input name="registration_number" maxLength={100}/></label><label className="field"><span>العملة</span><input name="currency" defaultValue="OMR" maxLength={3}/></label><label className="field"><span>نسبة الضريبة</span><input name="vat_rate" type="number" min="0" max="100" step="0.01" defaultValue="5"/></label><label className="field"><span>الموصل</span><select name="connector_id" defaultValue=""><option value="">بدون موصل</option>{connectors.map(c=><option value={c.id} key={c.id}>{c.country_code} · {c.provider_name} · {statuses[c.status]??c.status}</option>)}</select></label><label className="field" style={{display:"flex",gap:8,alignItems:"center"}}><input name="e_invoice_enabled" type="checkbox"/> تفعيل الفوترة الإلكترونية لهذا الملف</label><button className="btn primary" disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ الملف"}</button></form>
 <div className="card"><div className="card-title">موصلات الدول</div>{connectors.map(c=><div className="list-row" key={c.id}><strong>{names[c.country_code]??c.country_code} · {c.provider_name}</strong><span>{statuses[c.status]??c.status} · {c.integration_mode}</span></div>)}<div className="notice" style={{marginTop:14}}>الربط الحكومي الفعلي يحتاج بيانات اعتماد/تعاقدًا وواجهة API رسمية أو مزودًا معتمدًا. المنصة الآن تحفظ الإعداد والطابور ولا تنتحل إرسالًا حكوميًا.</div></div></section>
 <section className="card" style={{marginTop:20}}><div className="card-title">إرسال فاتورة إلكترونية</div><form className="grid three" onSubmit={queueSale}><label className="field"><span>الفاتورة</span><select name="sale_id" defaultValue="" required><option value="">اختر فاتورة صادرة</option>{sales.map(s=><option key={s.id} value={s.id}>#{s.invoice_no} · {s.total} · {s.issued_at?new Date(s.issued_at).toLocaleDateString("ar-OM"):"—"}</option>)}</select></label><label className="field"><span>الدولة</span><select name="country_code" defaultValue="OM"><option value="OM">عُمان</option><option value="SA">السعودية</option><option value="AE">الإمارات</option></select></label><div className="actions" style={{alignItems:"end"}}><button className="btn primary" disabled={queueBusy||sales.length===0}>{queueBusy?"جارٍ التجهيز…":"وضع في الطابور"}</button></div></form><div className="meta" style={{marginTop:10}}>الإرسال لا يبدأ فعليًا إلا عند وجود موصل رسمي حالته «مفعّل».</div></section>
 {message&&<div className="notice" role="status" style={{marginTop:14}}>{message}</div>}
 <section className="card" style={{marginTop:20}}><div className="card-title">ملفات الفوترة المحفوظة</div>{profiles.length===0?<div className="meta">لا توجد ملفات.</div>:profiles.map(p=><div className="list-row" key={p.id}><strong>{names[p.country_code]??p.country_code} · {p.store_id??"عام"}</strong><span>{p.e_invoice_enabled?"مفعّلة":"غير مفعّلة"} · VAT {p.vat_rate}%</span></div>)}</section>
 <section className="card" style={{marginTop:20}}><div className="card-title">سجل عمليات الفوترة الإلكترونية</div>{submissions.length===0?<div className="meta">لا توجد عمليات في الطابور.</div>:submissions.map(s=><div className="list-row" key={s.id}><div><strong>{names[s.country_code]??s.country_code} · {s.sale_id??"بدون فاتورة"}</strong><div className="meta">{new Date(s.created_at).toLocaleString("ar-OM")} · {s.external_reference??"—"}</div>{s.error_message&&<div className="meta">{s.error_code??"error"}: {s.error_message}</div>}</div><span className="status">{statuses[s.status]??s.status}</span></div>)}</section>
 </>;
}
