"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
type D={quotes:any[];vouchers:any[];priceLists:any[];priceItems:any[];products:any[];sales:any[];purchases:any[];customers:any[];suppliers:any[]};
const money=(n:any)=>Number(n||0).toLocaleString("en-OM",{minimumFractionDigits:3,maximumFractionDigits:3});
export default function CommercialPage(){
 const [d,setD]=useState<D|null>(null),[tab,setTab]=useState("quotes"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const [customer,setCustomer]=useState(""),[store,setStore]=useState(""),[party,setParty]=useState("customer"),[selectedList,setSelectedList]=useState(""),[statementRows,setStatementRows]=useState<any[]|null>(null);
 async function load(){const r=await fetch("/api/commercial?action=all",{cache:"no-store"});const x=await r.json();if(!r.ok)throw Error(x.error);setD(x);if(!store&&x.priceLists?.[0]?.store_id)setStore(x.priceLists[0].store_id);if(!selectedList&&x.priceLists?.[0]?.id)setSelectedList(x.priceLists[0].id);}
 useEffect(()=>{const id=window.setTimeout(()=>{void load().catch(e=>setMsg(e.message));},0);return()=>window.clearTimeout(id);},[]);
 const customers=d?.customers||[],suppliers=d?.suppliers||[],products=d?.products||[],priceLists=d?.priceLists||[];
 const customerName=(id:string)=>customers.find(x=>x.id===id)?.name||"—";
 const productName=(id:string)=>products.find(x=>x.id===id)?.name||"—";
 async function post(body:any){setBusy(true);setMsg("");try{const r=await fetch("/api/commercial",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x=await r.json();if(!r.ok)throw Error(x.error);setMsg("تم الحفظ");await load();}catch(e){setMsg(e instanceof Error?e.message:"خطأ")}finally{setBusy(false)}}
 const statement=statementRows;
 if(!d)return <main className="stage2-page"><div className="stage2-empty">{msg||"جارٍ تحميل المركز التجاري…"}</div></main>;
 return <main className="stage2-page">
  <header className="stage2-page-head"><div><div className="eyebrow">ERP التجاري</div><h1>المبيعات التجارية والفواتير</h1><p>عروض أسعار، سندات قبض وصرف، قوائم أسعار، وكشوف حساب — ضمن بيانات المؤسسة المعزولة.</p></div><Link className="btn" href="/dashboard/invoices">مركز الفواتير</Link></header>
  <nav className="stage2-tabs">{[["quotes","عروض الأسعار"],["vouchers","سندات القبض والصرف"],["prices","قوائم الأسعار"],["statements","كشوف الحساب"],["export","تصدير البيانات"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>
  {msg&&<div className="stage2-alert">{msg}</div>}
  {tab==="quotes"&&<section className="stage2-section">
   <div className="stage2-grid two"><form className="stage2-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post({action:"quote",store_id:String(f.get("store_id")),customer_id:String(f.get("customer_id")),valid_until:String(f.get("valid_until")),notes:String(f.get("notes")),lines:[{description:String(f.get("description")),product_id:String(f.get("product_id")),quantity:Number(f.get("quantity")),unit_price:Number(f.get("unit_price")),making_charge:Number(f.get("making_charge")),discount_amount:Number(f.get("discount_amount")),vat_amount:Number(f.get("vat_amount"))}]})}}><h2>عرض سعر جديد</h2><label>المتجر<input name="store_id" required defaultValue={store}/></label><label>العميل<select name="customer_id"><option value="">غير محدد</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المنتج<select name="product_id" required><option value="">اختر المنتج</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}{x.sku?" — "+x.sku:""}</option>)}</select></label><label>الوصف<input name="description" required/></label><label>الكمية<input name="quantity" defaultValue="1" inputMode="decimal"/></label><label>سعر الوحدة<input name="unit_price" defaultValue="0" inputMode="decimal"/></label><label>المصنعية<input name="making_charge" defaultValue="0" inputMode="decimal"/></label><label>الخصم<input name="discount_amount" defaultValue="0" inputMode="decimal"/></label><label>VAT<input name="vat_amount" defaultValue="0" inputMode="decimal"/></label><label>صالح حتى<input name="valid_until" type="date"/></label><label>ملاحظات<textarea name="notes"/></label><button className="btn btn-primary" disabled={busy}>إنشاء عرض سعر</button></form>
   <article className="stage2-panel"><h2>العروض الأخيرة</h2><div className="stage2-table-wrap"><table><thead><tr><th>العرض</th><th>الحالة</th><th>العميل</th><th>الإجمالي</th><th>إجراءات</th></tr></thead><tbody>{d.quotes.map(q=><tr key={q.id}><td>{q.quote_no}</td><td>{q.status}</td><td>{customerName(q.customer_id)}</td><td>{money(q.total)}</td><td><div className="actions">{q.status==="draft"&&<button className="btn" disabled={busy} onClick={()=>void post({action:"quote_status",quote_id:q.id,status:"sent"})}>إرسال</button>}{q.status==="sent"&&<button className="btn" disabled={busy} onClick={()=>void post({action:"quote_status",quote_id:q.id,status:"accepted"})}>قبول</button>}{q.status==="accepted"&&<button className="btn btn-primary" disabled={busy} onClick={()=>void post({action:"quote_convert",quote_id:q.id,payment_method:"cash"})}>تحويل إلى فاتورة</button>}</div></td></tr>)}</tbody></table></div></article></div>
  </section>}
  {tab==="vouchers"&&<section className="stage2-section"><div className="stage2-grid two"><form className="stage2-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post({action:"voucher",voucher_type:String(f.get("voucher_type")),party_type:String(f.get("party_type")),customer_id:String(f.get("customer_id")),supplier_id:String(f.get("supplier_id")),amount:Number(f.get("amount")),payment_method:String(f.get("payment_method")),reference:String(f.get("reference")),notes:String(f.get("notes"))})}}><h2>سند جديد</h2><label>النوع<select name="voucher_type"><option value="receipt">سند قبض</option><option value="payment">سند صرف</option></select></label><label>الطرف<select name="party_type"><option value="customer">عميل</option><option value="supplier">مورد</option><option value="other">أخرى</option></select></label><label>العميل<select name="customer_id"><option value="">—</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المورد<select name="supplier_id"><option value="">—</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المبلغ<input name="amount" required inputMode="decimal"/></label><label>طريقة الدفع<select name="payment_method"><option>cash</option><option>bank</option><option>card</option><option>wallet</option></select></label><label>المرجع<input name="reference"/></label><label>ملاحظات<textarea name="notes"/></label><button className="btn btn-primary" disabled={busy}>حفظ السند</button></form><article className="stage2-panel"><h2>السندات الأخيرة</h2><Table rows={d.vouchers} cols={["voucher_no","voucher_type","party_type","amount","payment_method","voucher_date"]} labels={["السند","النوع","الطرف","المبلغ","الدفع","التاريخ"]}/></article></div></section>}
  {tab==="prices"&&<section className="stage2-section"><div className="stage2-grid two"><form className="stage2-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post({action:"price_list",name:String(f.get("name")),store_id:String(f.get("store_id")),currency:String(f.get("currency")),valid_from:String(f.get("valid_from")),valid_until:String(f.get("valid_until"))})}}><h2>قائمة أسعار جديدة</h2><div className="stage2-form-grid"><label>الاسم<input name="name" required placeholder="أسعار التجزئة"/></label><label>المتجر<input name="store_id" defaultValue={store}/></label><label>العملة<input name="currency" defaultValue="OMR"/></label><label>من<input name="valid_from" type="date"/></label><label>إلى<input name="valid_until" type="date"/></label></div><button className="btn btn-primary" disabled={busy}>إنشاء القائمة</button></form><article className="stage2-panel"><h2>إضافة منتج للقائمة</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post({action:"price_item",price_list_id:String(f.get("price_list_id")),product_id:String(f.get("product_id")),sell_price:Number(f.get("sell_price")),buy_price:Number(f.get("buy_price")),making_charge:Number(f.get("making_charge"))})}}><label>قائمة الأسعار<select name="price_list_id" value={selectedList} onChange={e=>setSelectedList(e.target.value)} required>{priceLists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المنتج<select name="product_id" required><option value="">اختر</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}{x.sku?" — "+x.sku:""}</option>)}</select></label><label>سعر البيع<input name="sell_price" inputMode="decimal"/></label><label>سعر الشراء<input name="buy_price" inputMode="decimal"/></label><label>المصنعية<input name="making_charge" inputMode="decimal" defaultValue="0"/></label><button className="btn btn-primary" disabled={busy}>حفظ سعر المنتج</button></form></article></div><Table rows={(d.priceItems||[]).filter(x=>x.price_list_id===selectedList)} cols={["product_id","sell_price","buy_price","making_charge"]} labels={["المنتج","بيع","شراء","مصنعية"]} names={productName}/></section>}
  {tab==="statements"&&<section className="stage2-section"><div className="stage2-form-grid"><label>نوع الطرف<select value={party} onChange={e=>{setParty(e.target.value);setCustomer("")}}><option value="customer">عميل</option><option value="supplier">مورد</option></select></label><label>{party==="customer"?"العميل":"المورد"}<select value={customer} onChange={async e=>{const id=e.target.value;setCustomer(id);setStatementRows(null);if(id){try{const r=await fetch(`/api/commercial?action=statement&party_type=${party}&party_id=${encodeURIComponent(id)}`,{cache:"no-store"});const x=await r.json();if(!r.ok)throw Error(x.error);setStatementRows([...(x.sales||[]).map((v:any)=>({...v,entry_type:"sale"})),...(x.purchases||[]).map((v:any)=>({...v,entry_type:"purchase"})),...(x.vouchers||[]).map((v:any)=>({...v,entry_type:v.voucher_type}))]);}catch(err){setMsg(err instanceof Error?err.message:"خطأ")}}}}><option value="">اختر</option>{(party==="customer"?customers:suppliers).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{statement&&<Table rows={statement} cols={["entry_type","invoice_no","voucher_no","status","total","amount","created_at","voucher_date"]} labels={["النوع","فاتورة","سند","الحالة","المبلغ","قيمة السند","التاريخ","تاريخ السند"]}/>}</section>}
  {tab==="export"&&<section className="stage2-section"><article className="stage2-panel"><h2>تصدير البيانات</h2><p>يمكن تصدير القوائم الحالية من المتصفح بصيغة CSV دون منح أي صلاحيات إضافية.</p><div className="stage2-grid three"><Export title="الفواتير" rows={d.sales}/><Export title="المشتريات" rows={d.purchases}/><Export title="السندات" rows={d.vouchers}/></div></article></section>}
 </main>
}
function Table({rows,cols,labels,names}:{rows:any[];cols:string[];labels:string[];names?:(id:string)=>string}){return <div className="stage2-table-wrap"><table><thead><tr>{labels.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==="customer_id"&&names?names(r[c]):c==="total"||c==="subtotal"||c==="vat_amount"||c==="amount"?money(r[c]):String(r[c]??"—")}</td>)}</tr>)}</tbody></table></div>}
function Export({title,rows}:{title:string;rows:any[]}){const download=()=>{const keys=Object.keys(rows[0]||{});const csv=[keys.join(","),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??"")).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=title+".csv";a.click();URL.revokeObjectURL(a.href)};return <div className="stage2-panel"><h3>{title}</h3><p>{rows.length} سجل</p><button className="btn" onClick={download} disabled={!rows.length}>تصدير CSV</button></div>}
