import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const root = process.cwd();
const checks = [];
function ok(name, condition, detail = "") {
  if (!condition) throw new Error(`${name}${detail ? `: ${detail}` : ""}`);
  checks.push(name);
}
function text(path){ return readFileSync(join(root,path),"utf8"); }

ok("package.json exists", existsSync(join(root,"package.json")));
const pkg = JSON.parse(text("package.json"));
ok("Next is declared", Boolean(pkg.dependencies?.next));
ok("build script exists", typeof pkg.scripts?.build === "string");
ok("lint script exists", typeof pkg.scripts?.lint === "string");
ok("merchant camera API exists", existsSync(join(root,"app/api/merchant/cameras/route.ts")));
ok("merchant compliance API exists", existsSync(join(root,"app/api/merchant/compliance/route.ts")));
ok("merchant invoicing API exists", existsSync(join(root,"app/api/merchant/invoicing/route.ts")));
ok("camera dashboard exists", existsSync(join(root,"app/dashboard/cameras/page.tsx")));
ok("compliance dashboard exists", existsSync(join(root,"app/dashboard/compliance/page.tsx")));
ok("invoicing dashboard exists", existsSync(join(root,"app/dashboard/invoicing/page.tsx")));
ok("document intelligence API exists", existsSync(join(root,"app/api/merchant/documents/route.ts")));
ok("document intelligence dashboard exists", existsSync(join(root,"app/dashboard/documents/page.tsx")));
ok("webhook retry endpoint exists", existsSync(join(root,"app/api/cron/webhooks/route.ts")));
ok("WhatsApp retry endpoint exists", existsSync(join(root,"app/api/cron/whatsapp/route.ts")));
const whatsappRetry=text("supabase/migrations/20260919005000_gmp_whatsapp_retry_claim.sql");
ok("WhatsApp retry claim tracked", whatsappRetry.includes("for update skip locked") && whatsappRetry.includes("gmp_claim_due_whatsapp_messages"));
const webhookApi=text("app/api/dashboard/webhooks/route.ts");
ok("webhook destination validation wired", webhookApi.includes("validateWebhookUrl") && webhookApi.includes("invalid_webhook_destination"));
const webhooks=text("lib/webhooks.ts");
ok("webhook SSRF guard", webhooks.includes("dns/promises") && webhooks.includes('redirect:"error"') && webhooks.includes("webhook_destination_not_allowed"));
const storePage=text("app/store/[slug]/page.tsx");
ok("public store requires publication", storePage.includes("notFound()") && storePage.includes('eq("status","published")'));
const marketplaceLock=text("supabase/migrations/20260919000600_gmp_marketplace_rpc_security_hardening.sql");
ok("public marketplace RPC locked down", marketplaceLock.includes("revoke execute on function public.gmp_create_marketplace_order") && marketplaceLock.includes("from anon,authenticated"));
const migrationFiles = execFileSync("git",["ls-files","supabase/migrations"],{encoding:"utf8"}).split("\n").filter(Boolean);
ok("operational workflow migration tracked", migrationFiles.some(x=>x.includes("gmp_full_plan_operational_workflows_v1")));
ok("camera endpoint migration tracked", migrationFiles.some(x=>x.includes("gmp_camera_endpoint_hardening_v1")));
ok("invoicing hardening migration tracked", migrationFiles.some(x=>x.includes("gmp_harden_invoicing_rls_indexes_transitions_v1")));
ok("legacy Sukna execute lockdown tracked", migrationFiles.some(x=>x.includes("gmp_final_revoke_legacy_sukna_authenticated_execute_v1")));
const cameraApi=text("app/api/merchant/cameras/route.ts");
ok("camera API fail-closed", cameraApi.includes("requireMerchantPlan([\"business\"]") && cameraApi.includes("username || url.password"));
ok("camera API does not accept credentialed URL", cameraApi.includes("if (url.username || url.password) return null"));
const invoiceApi=text("app/api/merchant/invoicing/route.ts");
ok("country invoicing is explicit", invoiceApi.includes("OM") && invoiceApi.includes("SA") && invoiceApi.includes("AE"));
ok("government send is fail-closed", invoiceApi.includes("connector.status !== \"active\""));
ok("invoice API enforces transition allowlist", invoiceApi.includes("invalid_submission_transition") && invoiceApi.includes("transitions[current.status]"));
const complianceApi=text("app/api/merchant/compliance/route.ts");
ok("compliance API enforces transition allowlist", complianceApi.includes("invalid_case_transition") && complianceApi.includes("transitions[current.status]"));
const ci=text(".github/workflows/ci.yml");
ok("CI runs tests", ci.includes("npm test"));
ok("CI runs lint", ci.includes("npm run lint"));
ok("CI runs build", ci.includes("npm run build"));
const hardening=text("supabase/migrations/20260919000000_gmp_p0_p1_hardening.sql");
ok("marketplace abuse protection tracked", hardening.includes("gmp_public_order_rate_limits") && hardening.includes("gmp_allow_public_marketplace_order"));

ok("marketplace RPC execute lockdown tracked", marketplaceLock.includes("revoke execute on function public.gmp_create_marketplace_order") && marketplaceLock.includes("from anon,authenticated"));
ok("webhook retry hardening tracked", hardening.includes("gmp_claim_due_webhook_deliveries") && hardening.includes("dead_lettered"));
const launchIndexes=text("supabase/migrations/20260919004107_gmp_launch_fk_indexes.sql");
const remainingIndexes=text("supabase/migrations/20260919004139_gmp_remaining_fk_indexes.sql");
ok("Global Market FK index migrations tracked", launchIndexes.includes("gmp_ad_creatives_org_idx") && remainingIndexes.includes("gmp_display_content_screen_idx"));
const screenFkIndex=text("supabase/migrations/20260919004300_gmp_display_content_screen_id_index.sql");
ok("display content screen FK index tracked", screenFkIndex.includes("gmp_display_content_screen_id_idx"));
const billingClaim=text("supabase/migrations/20260919008100_gmp_billing_event_claim_v2.sql");
const einvoiceClaim=text("supabase/migrations/20260919006000_gmp_einvoice_send_claim.sql");
const complianceGuard=text("supabase/migrations/20260919007000_gmp_compliance_active_case_guard.sql");
ok("billing claim migration tracked", billingClaim.includes("gmp_claim_billing_event") && billingClaim.includes("for update") && billingClaim.includes("revoke execute"));
ok("e-invoice claim migration tracked", einvoiceClaim.includes("gmp_claim_einvoice_send") && einvoiceClaim.includes("for update") && einvoiceClaim.includes("revoke execute"));
ok("compliance active-case guard tracked", complianceGuard.includes("gmp_compliance_active_entity_uniq"));
const rlsConsolidation=text("supabase/migrations/20260919010000_gmp_rls_policy_consolidation.sql");\nok("RLS policy consolidation tracked", rlsConsolidation.includes("gmp_marketplace_listings_select") && rlsConsolidation.includes("gmp_store_directory_select") && rlsConsolidation.includes("admin_insert") && rlsConsolidation.includes("admin_update") && rlsConsolidation.includes("admin_delete"));
ok("health endpoint does not expose env names", !text("app/api/health/route.ts").includes("missingEnvironmentVariables"));
console.log(`verify-project: ${checks.length} checks passed`);
