"use client";
import {FormEvent,useEffect,useState} from "react";

type CaseRow={id:string;entity_type:string;entity_id:string|null;case_type:string;status:string;government_reference:string|null;connector_id:string|null;notes:string|null;created_at:string};
type Connector={id:string;country_code:string;provider_code:string;provider_name:string;integration_mode:string;status:string;capabilities:any};
type Gold={id:string;transaction_no:number;seller_name:string;seller_phone:string;weight_grams:number;karat:string|null;purchase_price:number;status:string;risk_level:string;created_at:string};
type Event={id:string;case_id:string;direction:string;event_type:string;occurred_at:string};
const labels:Record<string,string>={gold_purchase:"شراء ذهب",sale:"مبيعات",customer:"عميل",other:"أخرى",review:"مراجعة",suspicious:"اشتباه",report:"بلاغ",government_submission:"إرسال حكومي",open:"مفتوحة",under_review:"قيد المراجعة",submitted:"مرسلة",accepted:"مقبولة",rejected:"مرفوضة",closed:"مغلقة",failed:"فشلت",normal:"عادي",high:"مرتفع"};
export default function ComplianceWorkspace(){
 const[cases,setCases]=useState<CaseRow[]>([]),[events,setEvents]=useState<Event[]>([]),[connectors,setConnectors]=useState<Connector[]>([]),[gold,setGold]=useState<Gold[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/merchant/compliance",{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok){setMessage(d?.error??"تعذر التحميل");return;}setCases(d.cases??[]);setEvents(d.events??[]);setConnectors(d.connectors??[]);setGold(d.goldPurchases??[]);};useEffect(()=>{void load();},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage("");const obj=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/merchant/compliance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)});const d=await r.json().catch(()=>null);if(!r.ok)setMessage(d?.error??"تعذر الحفظ");else{e.currentTarget.reset();setMessage("تم إنشاء حالة الامتثال");await load();}setBusy(false);};
 const update=async(id:string,status:string)=>{const r=await fetch("/api/merchant/compliance",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.error??"تعذر التعديل");}else await load();};
 const addEvent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/merchant/compliance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"event",...body})});const d=await r.json().catch(()=>null);if(!r.ok)setMessage(d?.error??"تعذر تسجيل الحدث");else{e.currentTarget.reset();setMessage("تم تسجيل الحدث");await load();}};
 return <>
 <section className="grid two"><form className="card" onSubmit={submit}><div className="card-title">فتح حالة جديدة</div><label className="field"><span>نوع العملية</span><select name="entity_type" defaultValue="gold_purchase"><option value="gold_purchase">شراء ذهب من فرد</option><option value="sale">بيع</option><option value="customer">عميل</option><option value="repair">إصلاح</option><option value="other">أخرى</option></select></label><label className="field"><span>معرّف العملية (اختياري)</span><input name="entity_id" placeholder="UUID العملية" /></label><label className="field"><span>نوع الحالة</span><select name="case_type" defaultValue="review"><option value="review">مراجعة</option><option value="suspicious">اشتباه</option><option value="report">بلاغ</option><option value="government_submission">إرسال حكومي</option></select></label><label className="field"><span>موصل الدولة (اختياري)</span><select name="connector_id" defaultValue=""><option value="">بدون موصل</option>{connectors.map(c=><option value={c.id} key={c.id}>{c.country_code} · {c.provider_name} · {c.status}</option>)}</select></label><label className="field"><span>مرجع حكومي</span><input name="government_reference" /></label><label className="field"><span>ملاحظات</span><textarea name="notes" rows={4} /></label><button className="btn primary" disabled={busy}>{busy?"جارٍ الحفظ…":"فتح الحالة"}</button></form>
 <div className="card"><div className="card-title">جاهزية الربط الرسمي</div>{connectors.map(c=><div className="list-row" key={c.id}><strong>{c.country_code} · {c.provider_name}</strong><span>{labels[c.status]??c.status} · {c.integration_mode}</span></div>)}{connectors.length===0&&<div className="meta">لا توجد موصلات معرفة.</div>}<div className="notice" style={{marginTop:14}}>الحالة الحالية «مخطط» لا ترسل بيانات إلى جهة حكومية. عند تفعيل موصل رسمي سيُستخدم سجل الأحداث ومعرّف عدم التكرار وحالة الإرسال.</div></div></section>
 {message&&<div className="notice" role="status" style={{marginTop:14}}>{message}</div>}
 <section className="card" style={{marginTop:20}}><div className="card-title">مشتريات الذهب من الأفراد</div>{gold.length===0?<div className="meta">لا توجد مشتريات مسجلة.</div>:gold.map(g=><div className="list-row" key={g.id}><div><strong>#{g.transaction_no} · {g.seller_name}</strong><div className="meta">{g.weight_grams} غ · {g.karat??"—"} · {g.purchase_price} · مستوى المخاطر: {labels[g.risk_level]??g.risk_level}</div></div><form onSubmit={async e=>{e.preventDefault();const r=await fetch("/api/merchant/compliance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity_type:"gold_purchase",entity_id:g.id,case_type:g.risk_level==="high"?"suspicious":"review",notes:`فتح حالة من سجل شراء الذهب #${g.transaction_no}`})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.error??"تعذر فتح الحالة");}else{setMessage("تم فتح حالة مرتبطة بالعملية");await load();}}}><button className="btn" type="submit">فتح حالة</button></form></div>)}</section>
 <section className="card" style={{marginTop:20}}><div className="card-title">الحالات</div>{cases.length===0?<div className="meta">لا توجد حالات.</div>:cases.map(c=><article className="notice" key={c.id} style={{marginTop:10}}><div className="card-top"><strong>{labels[c.entity_type]??c.entity_type}{c.entity_id?` · ${c.entity_id.slice(0,8)}`:""}</strong><span className="status">{labels[c.status]??c.status}</span></div><div className="meta" style={{marginTop:6}}>{labels[c.case_type]??c.case_type} · {c.government_reference??"بدون مرجع حكومي"}</div>{c.notes&&<div style={{marginTop:6}}>{c.notes}</div>}<div className="actions" style={{marginTop:10}}>{c.status!=="under_review"&&c.status!=="closed"&&<button className="btn" onClick={()=>void update(c.id,"under_review")}>قيد المراجعة</button>}{c.status!=="closed"&&<button className="btn" onClick={()=>void update(c.id,"closed")}>إغلاق</button>}</div><form className="grid" style={{marginTop:10}} onSubmit={addEvent}><input type="hidden" name="case_id" value={c.id}/><input type="hidden" name="direction" value="internal"/><input name="event_type" placeholder="مثال: مراجعة الهوية مكتملة" maxLength={120} required/><button className="btn" type="submit">تسجيل حدث</button></form><div className="meta" style={{marginTop:8}}>الأحداث: {events.filter(e=>e.case_id===c.id).length}</div></article>)}</section>
 </>;
}
