-- Stage 2: merchant, marketplace, directory, displays and DOOH foundation.
-- Additive migration. Applied to Supabase as gmp_merchant_marketplace_stage2_core.

create table if not exists public.gmp_store_directory (
  store_id uuid primary key references public.gmp_stores(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft','published','suspended')),
  description text, category text, address text, city text, region text, postal_code text,
  latitude numeric, longitude numeric, website text,
  services jsonb not null default '[]'::jsonb, hours jsonb not null default '{}'::jsonb,
  social_links jsonb not null default '{}'::jsonb, verified_at timestamptz, published_at timestamptz,
  updated_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint gmp_store_directory_coordinates_check check (
    (latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)
  ),
  constraint gmp_store_directory_services_array check (jsonb_typeof(services) = 'array'),
  constraint gmp_store_directory_hours_object check (jsonb_typeof(hours) = 'object'),
  constraint gmp_store_directory_social_object check (jsonb_typeof(social_links) = 'object')
);

create table if not exists public.gmp_marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  store_id uuid not null references public.gmp_stores(id) on delete cascade,
  product_id uuid references public.gmp_products(id) on delete set null,
  listing_type text not null default 'product' check (listing_type in ('product','service')),
  title text not null, description text, category text,
  price numeric not null default 0 check (price >= 0),
  currency text not null default 'OMR',
  availability text not null default 'in_stock' check (availability in ('in_stock','limited','out_of_stock','on_request')),
  contact_mode text not null default 'contact' check (contact_mode in ('contact','request')),
  status text not null default 'draft' check (status in ('draft','active','paused','archived')),
  image_path text, metadata jsonb not null default '{}'::jsonb,
  created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.gmp_marketplace_orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity unique,
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  store_id uuid not null references public.gmp_stores(id) on delete cascade,
  buyer_user_id uuid, buyer_name text not null, buyer_phone text not null, buyer_email text,
  note text, status text not null default 'new' check (status in ('new','contacted','confirmed','fulfilled','cancelled')),
  fulfillment_mode text not null default 'contact' check (fulfillment_mode in ('contact','pickup','delivery')),
  subtotal numeric not null default 0 check (subtotal >= 0), currency text not null default 'OMR',
  source text not null default 'marketplace', idempotency_key text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.gmp_marketplace_order_lines (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.gmp_marketplace_orders(id) on delete cascade,
  listing_id uuid not null references public.gmp_marketplace_listings(id) on delete restrict,
  title_snapshot text not null, unit_price numeric not null check (unit_price >= 0),
  quantity numeric not null check (quantity > 0), line_total numeric not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.gmp_member_permissions (
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  permissions jsonb not null default '{}'::jsonb,
  created_by uuid, updated_at timestamptz not null default now(),
  primary key (organization_id,user_id),
  constraint gmp_member_permissions_object check (jsonb_typeof(permissions) = 'object')
);

create table if not exists public.gmp_display_content (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  store_id uuid not null references public.gmp_stores(id) on delete cascade,
  screen_id uuid references public.gmp_screens(id) on delete cascade,
  content_type text not null default 'text' check (content_type in ('text','market','gold','ad','listing')),
  title text not null, body text, media_path text,
  payload jsonb not null default '{}'::jsonb, active boolean not null default true, priority integer not null default 0,
  created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.gmp_display_schedules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  store_id uuid not null references public.gmp_stores(id) on delete cascade,
  screen_id uuid not null references public.gmp_screens(id) on delete cascade,
  content_id uuid not null references public.gmp_display_content(id) on delete cascade,
  starts_at timestamptz, ends_at timestamptz,
  days_of_week integer[] not null default '{}'::integer[], enabled boolean not null default true,
  created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint gmp_display_schedule_time_check check (ends_at is null or starts_at is null or ends_at >= starts_at),
  constraint gmp_display_schedule_days_check check (days_of_week <@ array[0,1,2,3,4,5,6]::integer[])
);

create table if not exists public.gmp_ad_creatives (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  campaign_id uuid not null references public.gmp_ad_campaigns(id) on delete cascade,
  name text not null, creative_type text not null default 'image' check (creative_type in ('image','video','html','text','url')),
  asset_path text, target_url text, metadata jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','approved','paused','archived')),
  created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.gmp_ad_placements (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.gmp_organizations(id) on delete cascade,
  campaign_id uuid not null references public.gmp_ad_campaigns(id) on delete cascade,
  creative_id uuid references public.gmp_ad_creatives(id) on delete set null,
  screen_id uuid references public.gmp_screens(id) on delete cascade,
  store_id uuid references public.gmp_stores(id) on delete cascade,
  status text not null default 'scheduled' check (status in ('scheduled','live','paused','completed','cancelled')),
  starts_at timestamptz, ends_at timestamptz, weight integer not null default 1 check (weight between 1 and 100),
  created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint gmp_ad_placement_scope_check check (screen_id is not null or store_id is not null),
  constraint gmp_ad_placement_time_check check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

create index if not exists gmp_store_directory_status_idx on public.gmp_store_directory(status,city,category);
create index if not exists gmp_marketplace_listings_public_idx on public.gmp_marketplace_listings(store_id,status,listing_type,updated_at desc);
create index if not exists gmp_marketplace_orders_store_idx on public.gmp_marketplace_orders(organization_id,store_id,created_at desc);
create index if not exists gmp_marketplace_order_lines_order_idx on public.gmp_marketplace_order_lines(order_id);
create index if not exists gmp_member_permissions_org_idx on public.gmp_member_permissions(organization_id);
create index if not exists gmp_display_content_screen_idx on public.gmp_display_content(store_id,screen_id,active,priority desc);
create index if not exists gmp_display_schedules_screen_idx on public.gmp_display_schedules(screen_id,enabled,starts_at,ends_at);
create index if not exists gmp_ad_creatives_campaign_idx on public.gmp_ad_creatives(campaign_id,status);
create index if not exists gmp_ad_placements_screen_idx on public.gmp_ad_placements(screen_id,status,starts_at,ends_at);

drop trigger if exists gmp_store_directory_updated_at on public.gmp_store_directory;
create trigger gmp_store_directory_updated_at before update on public.gmp_store_directory for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_marketplace_listings_updated_at on public.gmp_marketplace_listings;
create trigger gmp_marketplace_listings_updated_at before update on public.gmp_marketplace_listings for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_marketplace_orders_updated_at on public.gmp_marketplace_orders;
create trigger gmp_marketplace_orders_updated_at before update on public.gmp_marketplace_orders for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_member_permissions_updated_at on public.gmp_member_permissions;
create trigger gmp_member_permissions_updated_at before update on public.gmp_member_permissions for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_display_content_updated_at on public.gmp_display_content;
create trigger gmp_display_content_updated_at before update on public.gmp_display_content for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_display_schedules_updated_at on public.gmp_display_schedules;
create trigger gmp_display_schedules_updated_at before update on public.gmp_display_schedules for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_ad_creatives_updated_at on public.gmp_ad_creatives;
create trigger gmp_ad_creatives_updated_at before update on public.gmp_ad_creatives for each row execute function public.gmp_set_updated_at();
drop trigger if exists gmp_ad_placements_updated_at on public.gmp_ad_placements;
create trigger gmp_ad_placements_updated_at before update on public.gmp_ad_placements for each row execute function public.gmp_set_updated_at();

alter table public.gmp_store_directory enable row level security;
alter table public.gmp_marketplace_listings enable row level security;
alter table public.gmp_marketplace_orders enable row level security;
alter table public.gmp_marketplace_order_lines enable row level security;
alter table public.gmp_member_permissions enable row level security;
alter table public.gmp_display_content enable row level security;
alter table public.gmp_display_schedules enable row level security;
alter table public.gmp_ad_creatives enable row level security;
alter table public.gmp_ad_placements enable row level security;

drop policy if exists gmp_store_directory_public_read on public.gmp_store_directory;
create policy gmp_store_directory_public_read on public.gmp_store_directory for select to public using (status='published');
drop policy if exists gmp_store_directory_member_read on public.gmp_store_directory;
create policy gmp_store_directory_member_read on public.gmp_store_directory for select to authenticated using (
  exists(select 1 from public.gmp_stores s join public.gmp_organization_members m on m.organization_id=s.organization_id
  where s.id=gmp_store_directory.store_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_store_directory_admin_write on public.gmp_store_directory;
create policy gmp_store_directory_admin_write on public.gmp_store_directory for all to authenticated
using (exists(select 1 from public.gmp_stores s join public.gmp_organization_members m on m.organization_id=s.organization_id
where s.id=gmp_store_directory.store_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_stores s join public.gmp_organization_members m on m.organization_id=s.organization_id
where s.id=gmp_store_directory.store_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_marketplace_listings_public_read on public.gmp_marketplace_listings;
create policy gmp_marketplace_listings_public_read on public.gmp_marketplace_listings for select to public using (
  status='active' and exists(select 1 from public.gmp_store_directory d where d.store_id=gmp_marketplace_listings.store_id and d.status='published')
);
drop policy if exists gmp_marketplace_listings_member_read on public.gmp_marketplace_listings;
create policy gmp_marketplace_listings_member_read on public.gmp_marketplace_listings for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_listings.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_marketplace_listings_admin_write on public.gmp_marketplace_listings;
create policy gmp_marketplace_listings_admin_write on public.gmp_marketplace_listings for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_listings.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_listings.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_marketplace_orders_member_read on public.gmp_marketplace_orders;
create policy gmp_marketplace_orders_member_read on public.gmp_marketplace_orders for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_orders.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_marketplace_orders_admin_update on public.gmp_marketplace_orders;
create policy gmp_marketplace_orders_admin_update on public.gmp_marketplace_orders for update to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_orders.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_marketplace_orders.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_marketplace_order_lines_member_read on public.gmp_marketplace_order_lines;
create policy gmp_marketplace_order_lines_member_read on public.gmp_marketplace_order_lines for select to authenticated using (
  exists(select 1 from public.gmp_marketplace_orders o join public.gmp_organization_members m on m.organization_id=o.organization_id
  where o.id=gmp_marketplace_order_lines.order_id and m.user_id=(select auth.uid()))
);

drop policy if exists gmp_member_permissions_admin_all on public.gmp_member_permissions;
create policy gmp_member_permissions_admin_all on public.gmp_member_permissions for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_member_permissions.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_member_permissions.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_display_content_member_read on public.gmp_display_content;
create policy gmp_display_content_member_read on public.gmp_display_content for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_content.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_display_content_admin_write on public.gmp_display_content;
create policy gmp_display_content_admin_write on public.gmp_display_content for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_content.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_content.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_display_schedules_member_read on public.gmp_display_schedules;
create policy gmp_display_schedules_member_read on public.gmp_display_schedules for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_schedules.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_display_schedules_admin_write on public.gmp_display_schedules;
create policy gmp_display_schedules_admin_write on public.gmp_display_schedules for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_schedules.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_display_schedules.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_ad_creatives_member_read on public.gmp_ad_creatives;
create policy gmp_ad_creatives_member_read on public.gmp_ad_creatives for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_creatives.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_ad_creatives_admin_write on public.gmp_ad_creatives;
create policy gmp_ad_creatives_admin_write on public.gmp_ad_creatives for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_creatives.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_creatives.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

drop policy if exists gmp_ad_placements_member_read on public.gmp_ad_placements;
create policy gmp_ad_placements_member_read on public.gmp_ad_placements for select to authenticated using (
  exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_placements.organization_id and m.user_id=(select auth.uid()))
);
drop policy if exists gmp_ad_placements_admin_write on public.gmp_ad_placements;
create policy gmp_ad_placements_admin_write on public.gmp_ad_placements for all to authenticated
using (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_placements.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')))
with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=gmp_ad_placements.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));

-- Anonymous, payment-free order request. The merchant remains responsible for confirmation and fulfillment.
create or replace function public.gmp_create_marketplace_order(
  p_store_id uuid, p_buyer_name text, p_buyer_phone text, p_buyer_email text,
  p_note text, p_lines jsonb, p_fulfillment_mode text default 'contact', p_idempotency_key text default null
)
returns jsonb language plpgsql security definer set search_path to 'public'
as $function$
declare
  v_store public.gmp_stores%rowtype;
  v_line jsonb; v_listing public.gmp_marketplace_listings%rowtype;
  v_order uuid; v_order_no bigint; v_subtotal numeric := 0; v_qty numeric; v_listing_id uuid;
  v_key text := nullif(left(trim(coalesce(p_idempotency_key,'')),120),'');
begin
  if length(trim(coalesce(p_buyer_name,''))) < 2 or length(trim(coalesce(p_buyer_name,''))) > 120 then raise exception 'invalid_buyer_name'; end if;
  if length(trim(coalesce(p_buyer_phone,''))) < 5 or length(trim(coalesce(p_buyer_phone,''))) > 40 then raise exception 'invalid_buyer_phone'; end if;
  if p_fulfillment_mode not in ('contact','pickup','delivery') then raise exception 'invalid_fulfillment_mode'; end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines)=0 or jsonb_array_length(p_lines)>50 then raise exception 'invalid_order_lines'; end if;
  select s.* into v_store from public.gmp_stores s join public.gmp_store_directory d on d.store_id=s.id
    where s.id=p_store_id and d.status='published';
  if not found then raise exception 'store_not_available'; end if;
  if v_key is not null then
    select id,order_no into v_order,v_order_no from public.gmp_marketplace_orders where store_id=p_store_id and idempotency_key=v_key limit 1;
    if v_order is not null then return jsonb_build_object('success',true,'order_id',v_order,'order_no',v_order_no,'idempotent',true); end if;
  end if;
  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_listing_id := nullif(v_line->>'listing_id','')::uuid;
    v_qty := nullif(v_line->>'quantity','')::numeric;
    if v_listing_id is null or v_qty is null or v_qty<=0 or v_qty>100 then raise exception 'invalid_order_line'; end if;
    select l.* into v_listing from public.gmp_marketplace_listings l
      where l.id=v_listing_id and l.store_id=p_store_id and l.status='active';
    if not found then raise exception 'listing_not_available'; end if;
    if v_listing.availability='out_of_stock' then raise exception 'listing_out_of_stock'; end if;
    v_subtotal := v_subtotal + (v_listing.price*v_qty);
  end loop;
  insert into public.gmp_marketplace_orders(
    organization_id,store_id,buyer_user_id,buyer_name,buyer_phone,buyer_email,note,status,fulfillment_mode,subtotal,currency,source,idempotency_key
  ) values (
    v_store.organization_id,v_store.id,(select auth.uid()),left(trim(p_buyer_name),120),left(trim(p_buyer_phone),40),
    nullif(left(trim(coalesce(p_buyer_email,'')),160),''),nullif(left(trim(coalesce(p_note,'')),1000), ''),
    'new',p_fulfillment_mode,v_subtotal,v_store.currency,'marketplace',v_key
  ) returning id,order_no into v_order,v_order_no;
  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_listing_id := (v_line->>'listing_id')::uuid; v_qty := (v_line->>'quantity')::numeric;
    select title,price into v_listing.title,v_listing.price from public.gmp_marketplace_listings where id=v_listing_id;
    insert into public.gmp_marketplace_order_lines(order_id,listing_id,title_snapshot,unit_price,quantity,line_total)
      values(v_order,v_listing_id,v_listing.title,v_listing.price,v_qty,v_listing.price*v_qty);
  end loop;
  return jsonb_build_object('success',true,'order_id',v_order,'order_no',v_order_no,'subtotal',v_subtotal,'currency',v_store.currency,'status','new');
end;
$function$;

revoke execute on function public.gmp_create_marketplace_order(uuid,text,text,text,text,jsonb,text,text) from public;
grant execute on function public.gmp_create_marketplace_order(uuid,text,text,text,text,jsonb,text,text) to anon, authenticated;
