-- Applied commercial security/performance hardening v2
alter view public.gmp_gold_reconciliation set (security_invoker = true);
drop policy if exists gmp_sales_quotes_admin_write on public.gmp_sales_quotes; drop policy if exists gmp_sales_quotes_admin_insert on public.gmp_sales_quotes; drop policy if exists gmp_sales_quotes_admin_update on public.gmp_sales_quotes; drop policy if exists gmp_sales_quotes_admin_delete on public.gmp_sales_quotes;
drop policy if exists gmp_sales_quote_lines_admin_write on public.gmp_sales_quote_lines; drop policy if exists gmp_sales_quote_lines_admin_insert on public.gmp_sales_quote_lines; drop policy if exists gmp_sales_quote_lines_admin_update on public.gmp_sales_quote_lines; drop policy if exists gmp_sales_quote_lines_admin_delete on public.gmp_sales_quote_lines;
drop policy if exists gmp_cash_vouchers_admin_write on public.gmp_cash_vouchers; drop policy if exists gmp_cash_vouchers_admin_insert on public.gmp_cash_vouchers; drop policy if exists gmp_cash_vouchers_admin_update on public.gmp_cash_vouchers; drop policy if exists gmp_cash_vouchers_admin_delete on public.gmp_cash_vouchers;
drop policy if exists gmp_price_lists_admin_write on public.gmp_price_lists; drop policy if exists gmp_price_lists_admin_insert on public.gmp_price_lists; drop policy if exists gmp_price_lists_admin_update on public.gmp_price_lists; drop policy if exists gmp_price_lists_admin_delete on public.gmp_price_lists;
drop policy if exists gmp_price_list_items_admin_write on public.gmp_price_list_items; drop policy if exists gmp_price_list_items_admin_insert on public.gmp_price_list_items; drop policy if exists gmp_price_list_items_admin_update on public.gmp_price_list_items; drop policy if exists gmp_price_list_items_admin_delete on public.gmp_price_list_items;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['gmp_sales_quotes','gmp_cash_vouchers','gmp_price_lists'] LOOP EXECUTE format('create policy %I on public.%I for insert to authenticated with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin'')))',t||'_admin_insert',t,t); EXECUTE format('create policy %I on public.%I for update to authenticated using (exists(select 1 from public.gmp_organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin''))) with check (exists(select 1 from public.gmp_organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin'')))',t||'_admin_update',t,t,t); EXECUTE format('create policy %I on public.%I for delete to authenticated using (exists(select 1 from public.gmp_organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin'')))',t||'_admin_delete',t,t); END LOOP; END $$;
create policy gmp_sales_quote_lines_admin_insert on public.gmp_sales_quote_lines for insert to authenticated with check (exists(select 1 from public.gmp_sales_quotes q join public.gmp_organization_members m on m.organization_id=q.organization_id where q.id=gmp_sales_quote_lines.quote_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy gmp_sales_quote_lines_admin_update on public.gmp_sales_quote_lines for update to authenticated using (exists(select 1 from public.gmp_sales_quotes q join public.gmp_organization_members m on m.organization_id=q.organization_id where q.id=gmp_sales_quote_lines.quote_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin'))) with check (exists(select 1 from public.gmp_sales_quotes q join public.gmp_organization_members m on m.organization_id=q.organization_id where q.id=gmp_sales_quote_lines.quote_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy gmp_sales_quote_lines_admin_delete on public.gmp_sales_quote_lines for delete to authenticated using (exists(select 1 from public.gmp_sales_quotes q join public.gmp_organization_members m on m.organization_id=q.organization_id where q.id=gmp_sales_quote_lines.quote_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy gmp_price_list_items_admin_insert on public.gmp_price_list_items for insert to authenticated with check (exists(select 1 from public.gmp_price_lists p join public.gmp_organization_members m on m.organization_id=p.organization_id where p.id=gmp_price_list_items.price_list_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy gmp_price_list_items_admin_update on public.gmp_price_list_items for update to authenticated using (exists(select 1 from public.gmp_price_lists p join public.gmp_organization_members m on m.organization_id=p.organization_id where p.id=gmp_price_list_items.price_list_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin'))) with check (exists(select 1 from public.gmp_price_lists p join public.gmp_organization_members m on m.organization_id=p.organization_id where p.id=gmp_price_list_items.price_list_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy gmp_price_list_items_admin_delete on public.gmp_price_list_items for delete to authenticated using (exists(select 1 from public.gmp_price_lists p join public.gmp_organization_members m on m.organization_id=p.organization_id where p.id=gmp_price_list_items.price_list_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create index if not exists gmp_cash_vouchers_branch_idx on public.gmp_cash_vouchers(branch_id); create index if not exists gmp_cash_vouchers_customer_idx on public.gmp_cash_vouchers(customer_id); create index if not exists gmp_cash_vouchers_supplier_idx on public.gmp_cash_vouchers(supplier_id);