-- Central Gold Ledger scope hardening, production-applied 2026-09-23.
CREATE OR REPLACE FUNCTION public.gmp_post_gold_ledger_entry(p_organization_id uuid, p_branch_id uuid, p_store_id uuid, p_product_id uuid, p_operation_type text, p_direction text, p_reference_type text, p_reference_id uuid, p_idempotency_key text, p_karat numeric, p_gross_weight_grams numeric, p_stone_weight_grams numeric, p_net_weight_grams numeric, p_unit_value numeric, p_making_charge numeric, p_total_value numeric, p_currency text DEFAULT 'OMR'::text, p_metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$ declare v_actor uuid := (select auth.uid()); v_entry public.gmp_gold_ledger_entries%rowtype; begin if v_actor is null then raise exception 'authentication required'; end if; if not exists(select 1 from public.gmp_organization_members m where m.organization_id=p_organization_id and m.user_id=v_actor and m.role in ('owner','admin')) then raise exception 'not authorized'; end if;
 if p_branch_id is not null and not exists(select 1 from public.gmp_branches b where b.id=p_branch_id and b.organization_id=p_organization_id and b.active) then raise exception 'branch scope invalid'; end if;
 if p_store_id is not null and not exists(select 1 from public.gmp_stores s where s.id=p_store_id and s.organization_id=p_organization_id and (p_branch_id is null or s.branch_id=p_branch_id)) then raise exception 'store scope invalid'; end if;
 if p_product_id is not null and not exists(select 1 from public.gmp_products pr join public.gmp_stores s on s.id=pr.store_id where pr.id=p_product_id and s.organization_id=p_organization_id and (p_store_id is null or pr.store_id=p_store_id) and pr.active) then raise exception 'product scope invalid'; end if; if p_karat <= 0 or p_karat > 24 then raise exception 'invalid_karat'; end if; if p_gross_weight_grams < 0 or p_stone_weight_grams < 0 or p_net_weight_grams < 0 then raise exception 'invalid_weight'; end if; if p_net_weight_grams > p_gross_weight_grams then raise exception 'net_weight_exceeds_gross'; end if; if p_unit_value < 0 or p_making_charge < 0 or p_total_value < 0 then raise exception 'invalid_value'; end if; if p_operation_type not in ('purchase','sale','sale_return','purchase_return','transfer_in','transfer_out','buyback','exchange_in','exchange_out','manufacture_in','manufacture_out','repair_in','repair_out','adjustment') then raise exception 'invalid_operation_type'; end if; if p_direction not in ('in','out') then raise exception 'invalid_direction'; end if; if p_currency is null or length(trim(p_currency)) <> 3 then raise exception 'invalid_currency'; end if; if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then raise exception 'invalid_metadata'; end if; if p_idempotency_key is not null then select * into v_entry from public.gmp_gold_ledger_entries where organization_id=p_organization_id and idempotency_key=p_idempotency_key limit 1; if found then return jsonb_build_object('success',true,'entry_id',v_entry.id,'idempotent',true); end if; end if; insert into public.gmp_gold_ledger_entries(organization_id,branch_id,store_id,product_id,operation_type,direction,reference_type,reference_id,idempotency_key,karat,gross_weight_grams,stone_weight_grams,net_weight_grams,unit_value,making_charge,total_value,currency,metadata,created_by) values(p_organization_id,p_branch_id,p_store_id,p_product_id,p_operation_type,p_direction,nullif(trim(p_reference_type),''),p_reference_id,nullif(trim(p_idempotency_key),''),p_karat,p_gross_weight_grams,p_stone_weight_grams,p_net_weight_grams,p_unit_value,p_making_charge,p_total_value,upper(trim(p_currency)),p_metadata,v_actor) returning * into v_entry; return jsonb_build_object('success',true,'entry_id',v_entry.id,'idempotent',false,'pure_gold_weight_grams',v_entry.pure_gold_weight_grams); end; $function$
;
