import Link from "next/link";

const plans = [
  { name: "الشاشة", monthly: "5", halfYear: "25", yearly: "50", extraDiscount: "2.5%", eyebrow: "DISPLAY", description: "للواجهة الاحترافية وعرض أسعار السوق داخل المحل.", features: ["شاشة المحل الأساسية", "أسعار الذهب والفضة", "محتوى وعروض المحل", "قوالب الشاشة", "تحديث تلقائي"] },
  { name: "الأعمال", monthly: "25", halfYear: "125", yearly: "240", extraDiscount: "5%", eyebrow: "OPERATIONS", description: "لتشغيل المبيعات والمشتريات والمصاريف من مساحة واحدة.", features: ["المبيعات وPOS", "المشتريات والموردون", "المصاريف والصندوق", "العملاء والأصناف", "الفواتير والتقارير الأساسية"] },
  { name: "الكاملة", monthly: "46", halfYear: "247", yearly: "450", extraDiscount: "8%", eyebrow: "FULL WORKSPACE", description: "للتشغيل المتكامل مع المخزون والامتثال والأتمتة المتقدمة.", features: ["كل مزايا الأعمال", "AI/OCR", "شراء الذهب من الأفراد", "الإصلاحات وتتبع القطعة", "المخزون والجرد والفروع", "المحاسبة والضرائب المتقدمة", "الموافقات وسجل التدقيق"] },
];

export default function PricingPage() {
  return <div className="page-frame pricing-page">
    <header className="topbar"><div className="container nav site-nav"><Link href="/" className="brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></Link><nav className="nav-links" aria-label="Primary"><Link href="/gold">الذهب</Link><Link href="/silver">الفضة</Link><Link href="/markets">الأسواق</Link><Link href="/news">الأخبار</Link></nav><div className="nav-actions"><Link className="btn btn-ghost" href="/login">تسجيل الدخول</Link><Link className="btn btn-primary" href="/demo">ابدأ الآن</Link></div></div></header>
    <main className="container site-main section-shell">
      <section className="page-hero"><div className="page-hero-grid"><div><div className="eyebrow"><span className="live-dot" />PLANS & TOOLS</div><h1>اختر مستوى التشغيل المناسب لمحلك.</h1><p className="page-lede">ابدأ بالشاشة، ثم وسّع إلى إدارة الأعمال، أو استخدم مساحة التشغيل الكاملة عندما تحتاج المبيعات والمخزون والمحاسبة والامتثال في نظام واحد.</p><div className="actions" style={{marginTop:26}}><Link href="/demo" className="btn btn-primary btn-lg">جرّب المنصة</Link><Link href="/login" className="btn btn-lg">لديك حساب؟ دخول</Link></div></div><aside className="hero-panel"><div className="eyebrow">ADD-ON DISPLAY</div><div className="panel-value">4 ر.ع</div><div className="panel-meta">للشاشة الإضافية · شهريًا</div><div className="plan-periods" style={{marginTop:17}}><span className="plan-period">21 ر.ع · 6 أشهر</span><span className="plan-period">44 ر.ع · سنة</span></div></aside></div></section>
      <section className="plan-grid">{plans.map((plan,index)=><article className={`plan-card ${index===1?"featured":""}`} key={plan.name}><div className="plan-head"><div><div className="plan-number">{plan.eyebrow}</div><div className="plan-name">{plan.name}</div></div><span className="status">خصم الفروع {plan.extraDiscount}</span></div><p className="meta" style={{margin:"13px 0 0",lineHeight:1.7}}>{plan.description}</p><div className="plan-price">{plan.monthly} <small>ر.ع / شهر</small></div><div className="plan-periods"><span className="plan-period">6 أشهر: {plan.halfYear} ر.ع</span><span className="plan-period">سنة: {plan.yearly} ر.ع</span></div><div className="plan-features">{plan.features.map(feature=><div className="plan-feature" key={feature}><span>✓</span>{feature}</div>)}</div><Link href={`/demo?plan=${encodeURIComponent(plan.name)}`} className="btn btn-primary">ابدأ مع {plan.name}</Link></article>)}</section>
      <div className="plan-note">الأسعار المعروضة لخطط المنصة التجارية كما هي مضبوطة حاليًا في النظام. الخدمات المقيدة بالباقة تظهر داخل لوحة المحل بحسب الاشتراك والصلاحيات.</div>
    </main>
  </div>;
}
