import Link from "next/link";
import MoneyDisplay from "../../components/MoneyDisplay";
import { ADDITIONAL_SCREEN_PRICING, MERCHANT_PLANS } from "../../lib/saas-plans";



export default function PricingPage() {
  return <div className="page-frame pricing-page">
    <header className="topbar"><div className="container nav site-nav"><Link href="/" className="brand"><span className="brand-mark">GM</span><span>GLOBAL <b>MARKET</b></span></Link><nav className="nav-links" aria-label="التنقل الرئيسي"><Link href="/gold">الذهب</Link><Link href="/silver">الفضة</Link><Link href="/markets">الأسواق</Link><Link href="/stocks">الأسهم</Link><Link href="/currencies">العملات</Link><Link href="/news">الأخبار</Link></nav><div className="nav-actions"><Link className="btn btn-ghost" href="/login">تسجيل الدخول</Link><Link className="btn btn-primary" href="/demo">ابدأ الآن</Link></div></div></header>
    <main className="container site-main section-shell">
      <section className="page-hero"><div className="page-hero-grid"><div><div className="eyebrow"><span className="live-dot" />الباقات والأدوات</div><h1>اختر مستوى التشغيل المناسب لمحلك.</h1><p className="page-lede">ابدأ بالشاشة، ثم وسّع إلى إدارة الأعمال، أو استخدم مساحة التشغيل الكاملة عندما تحتاج المبيعات والمخزون والمحاسبة والامتثال في نظام واحد.</p><div className="actions" style={{marginTop:26}}><Link href="/demo" className="btn btn-primary btn-lg">جرّب المنصة</Link><Link href="/login" className="btn btn-lg">لديك حساب؟ دخول</Link></div></div><aside className="hero-panel"><div className="eyebrow">شاشة إضافية</div><div className="panel-value"><MoneyDisplay value={ADDITIONAL_SCREEN_PRICING.monthly} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /></div><div className="panel-meta">للشاشة الإضافية · شهريًا</div><div className="plan-periods" style={{marginTop:17}}><span className="plan-period"><MoneyDisplay value={ADDITIONAL_SCREEN_PRICING.halfYear} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /> · 6 أشهر</span><span className="plan-period"><MoneyDisplay value={ADDITIONAL_SCREEN_PRICING.yearly} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /> · سنة</span></div></aside></div></section>
      <section className="plan-grid">{MERCHANT_PLANS.map((plan,index)=><article className={"plan-card " + (index===1?"featured":"")} key={plan.code}><div className="plan-head"><div><div className="plan-number">{plan.eyebrow}</div><div className="plan-name">{plan.name}</div></div><span className="status">خصم الفروع {plan.extraBranchDiscount}</span></div><p className="meta" style={{margin:"13px 0 0",lineHeight:1.7}}>{plan.description}</p><div className="plan-price"><MoneyDisplay value={plan.monthly} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /> <small>/ شهر</small></div><div className="plan-periods"><span className="plan-period">6 أشهر: <MoneyDisplay value={plan.halfYear} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /></span><span className="plan-period">سنة: <MoneyDisplay value={plan.yearly} currency="OMR" locale="ar-OM" maximumFractionDigits={0} /></span></div><div className="plan-features">{plan.features.map(feature=><div className="plan-feature" key={feature}><span>✓</span>{feature}</div>)}</div><div className="plan-actions"><Link href={"/login?next=" + encodeURIComponent("/dashboard/integrations?plan=" + plan.code)} className="btn btn-primary">متابعة {plan.name}</Link><Link href={"/signup?plan=" + plan.code + "&next=" + encodeURIComponent("/dashboard/integrations")} className="btn">إنشاء حساب</Link></div></article>)}</section>
      <div className="plan-note">الأسعار المعروضة لخطط المنصة التجارية كما هي مضبوطة حاليًا في النظام. الخدمات المقيدة بالباقة تظهر داخل لوحة المحل بحسب الاشتراك والصلاحيات.</div>
    </main>
  </div>;
}
